### ISSUE TITLE
Grpc error - TypeError: Incorrectly typed arguments to startBatch

### ISSUE THREAD

**Issue by ashishchandr70** [grpc/grpc-node#1025]
### Problem description

I am using the Hyperledger Fabric Node Application SDK to invoke an example smart contract (details [here ](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1381)if interested). The example contract works fine and I can invoke it from within the docker container where hyperledger/fabric runtime exists.

 

However, when I try to invoke it using an application SDK API, I get an error `TypeError: Incorrectly typed arguments to startBatch` which I have traced to function _`startBatchIfReady (<path>/node_modules/grpc/src/client_interceptors.js:752:10)`. Here is the complete stack trace:

 

```

Exception has occurred: TypeError

TypeError: Incorrectly typed arguments to startBatch

    at _startBatchIfReady (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:752:10)

    at Object.final_requester.start (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:801:21)

    at InterceptingCall._callNext (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:421:43)

    at InterceptingCall.start (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:456:8)

    at next (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:453:22)

    at InterceptingCall._callNext (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:428:12)

    at InterceptingCall.start (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/grpc/src/client_interceptors.js:456:8)

    at ServiceClient.Client.makeUnaryRequest (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/grpc/src/client.js:537:21)

    at ServiceClient.method_func (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/grpc/src/client.js:952:43)

    at Promise (/usr/local/fabric/fabric-samples/fabcar/javascript/node_modules/fabric-client/lib/Peer.js:194:27)

```

 

The weird thing is that the same node.js script works from my personal Ubuntu laptop using the same configuration of Hyperledger Fabric which in turn uses gRPC. 

My feeling is that it is something **specific to my environment but I do not know what**.

### Reproduction steps

 

1. Download and install Hyperledger Fabric using instructions provided [here](https://hyperledger-fabric.readthedocs.io/en/release-1.4/install.html).

2. Go to the <your fabric installation path>/fabric-samples/fabcar directory and execute `./startFabric.sh javascript`. This will bring up the fabcar example's Fabric runtime (running inside of a docker container).

3. Follow the directions at the end of the script execution (they are printed).

4. Go to the <your fabric installation path>/fabric-samples/fabcar/javascript directory and execute

```

node enrollAdmin

node registerUser

node query <= it fails with the error on this script, specifically when invoking

          const network = await gateway.getNetwork('mychannel');

 

```

 

### Environment

- RHEL 7.6 'Maipo' x64
- Node version 8.16.0 installed through tar.gz tarball.
- gRPC's node binary is being used. I see a folder node-v69-linux-x64-glibc which has grpc_node.node executable.

 
### Additional context

The Linux VM has no access to open internet but we have access to an alternative npm registry and the VM can access other intranet resources as needed (alternate docker registry etc.).

**Comment by murgatroid99** [comment]
That error message indicates that something of the wrong type is being passed to the gRPC API. It looks like at least one interceptor is in use, so it's possible that that interceptor is outputting something of the wrong type. In short, this seems like a bug with Hyperledger Fabric, and you should file an issue with them.

**Comment by ashishchandr70** [comment]
Thanks @murgatroid99. I already have an open issue with Hyperledger team. I will quote your reply to them.

However, why would the same code work on my laptop and in all other environments? Any ideas?

**Comment by murgatroid99** [comment]
I think it's most likely that the Hyperledger Fabric code is somehow behaving differently on different platforms.

**Comment by ashishchandr70** [comment]
Thanks again Michael. After your last comment, what I did was move away from my internet-restricted environment and spun up a RHEL 7 instance on AWS.

I installed Hyperledger/Fabric on it and then tried to execute the steps I have mentioned in this issue. I was able to successfully invoke `node query.js` which tells me that HLF is also working as it should and it is probably something environmental on my end.

Is there any guidance you can provide in terms of versions? I have

Node: v8.16.0
Npm: v6.4.1

In the <path>/node_modules/grpc/src/node/extension_binary, I see two folders:
node-v57-linux-x64-glibc
node-v69-linux-x64-glibc

Am I missing a dependency or the correct version? 

Thanks again.

**Comment by murgatroid99** [comment]
Those look fine. If those binaries were wrong, you would get a big error about loading gRPC and you wouldn't get as far as making a request.

**Comment by ashishchandr70** [comment]
Thanks. It appears to be going for node-v57-linux-x64-glibc folder's binary as I tried renaming the two folders and it complained on this one.

Is this compatble with node version 8.16.0 and npm version 6.4.1?

I also peeked inside the fabric runtime docker container and it is using grpc v1.17.0 and using node-v57-linux-x64-glibc precompiled binary. However, the application is wanting to link to grpc v1.21.1 and I have the same node-v57-linux-x64-glibc folder under the application's node_modules/grpc/src/node/extension_binary folder.

**Comment by murgatroid99** [comment]
I said those are fine. If they weren't compatible, they wouldn't be loading properly at all.

If you are using different versions of gRPC in the different environments, that could explain why you are seeing the bug with one but not the other. If I understand right, you are only seeing this bug with the older version. In that case it may just be a bug in the gRPC library that has been fixed.

**Comment by ashishchandr70** [comment]
I guess I am not calling it a bug because it works on my laptop and on AWS. However, given our internet access restrictions, a lot of the stuff has had to be manually installed, not by using yum.

The issue I am seeing is at the application SDK level where I believe it is trying to use node-v57-linux-x64-glibc through gRPC v1.21.1. 

The fabric runtime is within a docker container where it is using node-v57-linux-x64-glibc binary with gRPC v1.17.0. 

The issue is from Application SDK --> Fabric Runtime inside the container with the above gRPC configs.

I know this is not your issue because I am sure it is something environmental on my end, so I appreciate your taking the time, and sorry for the trouble.

**Comment by murgatroid99** [comment]
OK, I just want to understand this: what version of the grpc library is being used by the code that is throwing the error?

**Comment by ashishchandr70** [comment]
gRPC v1.21.1 which has  node-v57-linux-x64-glibc related binary.

**Comment by ashishchandr70** [comment]
Also Michael @murgatroid99 before you do any more checking, I would like to thoroughly retrace my steps. Since we have internet restrictions, I did a lot of manual copying and I want to make sure that the grpc folder under node_modules wasn't copied from a different version of grpc (core Fabric uses gRPC v1.17.0). 

I will report back tomorrow. Thanks for all your help and advice today.

**Comment by ashishchandr70** [comment]
It was my own mistake - I had mixed up grpc v1.17.0 node-v57-linux-x64-glibc and copied that over to the grpc v1.21.1's folder structure. 

Thanks for all your help yesterday @murgatroid99.

**Comment by yab119074412** [comment]
we have internet restrictions too and have to operate manually. The grpc required node-v48-linux-x64-glibc, and we installed node-v64-linux-x64-glibc . but when I replaced it with 48, I have met the same problem as you. Can you give me a little advice to resolve it? thanks! @ashishchandr70,

**Comment by murgatroid99** [comment]
@yab119074412 The problem that @ashishchandr70 had was a mismatch between the versions of the grpc library and the binary file. What version of the grpc library are you using? Where did you get that binary file, and what version did you get?

**Comment by yab119074412** [comment]
nodejs, and the version of grpc is 1.23.3. I install it using "npm i grpc" on a virtual machine first, then I migrate the package to an offline machine, and the screen prompts me to use "npm rebuild", but the offline machine could not do that.

**Comment by murgatroid99** [comment]
The binary file is specific to the Node version, operating system, processor architecture, and libc implementation. If any of those are different on the system you are using the library on, you need to specify that when installing the library. The arguments for that are listed in the [node-pre-gyp README](https://www.npmjs.com/package/node-pre-gyp). Alternatively, the message you got says what binary name it is looking for. If you share that, I can give you the argument list to get the proper binary.
