### ISSUE TITLE
Connections remain open after shut down

### ISSUE THREAD

**Issue by JrSchild** [grpc/grpc-node#1080]
### Problem description
Connections remain open after invoking `tryShutdown` and `forceShutdown` in tests.

### Reproduction steps
```
git clone git@github.com:JrSchild/grpc-open-connetions.git grpc-open-connetions
cd grpc-open-connetions
npm install
npm run test
```

Which produces the following output:
```
 PASS  ./test.spec.js
  ✓ should shut the server down (2ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.376s, estimated 1s
Ran all test suites matching /test.spec.js/i.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Timeout

      at new SubchannelPool (node_modules/@grpc/grpc-js/build/src/subchannel-pool.js:38:13)
      at Object.<anonymous> (node_modules/@grpc/grpc-js/build/src/subchannel-pool.js:99:30)
```

Our tests require reconnecting with grpc. Unfortunately we cannot reliably test this because the connection remains open after shutting down.
Edit: The `setInterval` created in `subchannel-pool` is never cleaned up. It could maybe be fixed by clearing the interval when the pool is empty and starting it again when there is 0 < channelTargets.

### Environment
 - OS name, version and architecture: [Mac OS X 10.14.5]
 - Node version [12.6.0]
 - Node installation method [nvm]
 - Package name and version [gRPC@0.6.9]

**Comment by murgatroid99** [comment]
That `setInterval` is explicitly `unref`ed so that the process can exit even while that timer is active. Jest may not be properly detecting that. All connections are also `unref`ed as long as they do not have any active requests.

**Comment by JrSchild** [comment]
Thank you @murgatroid99, I will verify this tomorrow.

**Comment by merlinnot** [comment]
@murgatroid99 I believe there should be an API that allows users to close the created server. Unref-ing only works if users intend to exit the entire process, but that might not always be the case.

**Comment by murgatroid99** [comment]
First, this is about client connections. Servers are handled differently. Second, connections are automatically closed if no open clients are using them, and clients can be explicitly closed. And third, this issue is about things holding the process open. If the user doesn't want to close the process, there's no issue.

**Comment by merlinnot** [comment]
s/server/client/

Sorry, it was late in my time zone 🙃

I have a similar issue with Firestore and “connections are automatically closed if no open clients are using them”  is in contradiction with https://github.com/googleapis/nodejs-firestore/issues/769#issuecomment-537151198. Could you elaborate on it a little more?

**Comment by merlinnot** [comment]
Does “using” mean that you have to close the client, or just don’t perform any operations?

**Comment by murgatroid99** [comment]
I mean that connections are closed if no clients hold references to them. But since connections are also unrefed as long as there are no active requests, they still shouldn't hold the process open.

I am also describing the functionality of the latest version of grpc-js, which I believe had not been picked up by Firestore at the time that you filed the linked issue.
