### ISSUE TITLE
DNS Resolver - Failed to parse target GCS bucket

### ISSUE THREAD

**Issue by zerefel** [grpc/grpc-node#1159]
### Problem description
Using `"@google-cloud/pubsub": "^1.1.5"`, cannot obtain an existing subscription for a GCS bucket, or create a new one.

### Reproduction steps
Here's the reproduction code. A GCS bucket with a Pub/Sub topic and a subscription have already been set up.

```js
const pubsubSubscribe = async params => {
    const topic = pubsub.topic(params.topic);
    const result = await topic.subscription(params.subscription, params.options);
        
    return result;
};

const sub = await pubsubSubscribe({
    topic: 'existing-topic',
    subscription: 'existing-subscription'
});
```

### Environment
 - Docker environment `FROM node:10.16`
 - Node version 10.16
 - `"@grpc/grpc-js": "^0.6.5"`

### Additional context
* The exact same code used to work with a previous version of `@google-cloud/pubsub`, and it stopped working after doing a clean build with docker cache disabled. I tried rolling back `grpc` and `@google-cloud/pubsub` to multiple older versions to no avail. We cannot roll back to a working version because we run into weird incompatibilities between `@google-cloud/pubsub` and the old grpc (pre-`@grpc/grpc-js`).

* Stack trace:
```
cloud_1          | uncaughtException: Failed to parse target storage.googleapis.com:undefined
cloud_1          | Error: Failed to parse target storage.googleapis.com:undefined
cloud_1          |     at Function.getDefaultAuthority (/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver-dns.js:253:15)
cloud_1          |     at Object.getDefaultAuthority (/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver.js:73:32)
cloud_1          |     at new ChannelImplementation (/usr/src/app/node_modules/@grpc/grpc-js/build/src/channel.js:85:48)
cloud_1          |     at new Client (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:37:36)
cloud_1          |     at new ServiceClientImpl (/usr/src/app/node_modules/@grpc/grpc-js/build/src/make-client.js:49:5)
cloud_1          |     at GrpcClient.createStub (/usr/src/app/node_modules/google-gax/build/src/grpc.js:236:22)
cloud_1          |     at process._tickCallback (internal/process/next_tick.js:68:7) {"error":{},"stack":"Error: Failed to parse target storage.googleapis.com:undefined\n    at Function.getDefaultAuthority (/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver-dns.js:253:15)\n    at Object.getDefaultAuthority (/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver.js:73:32)\n    at new ChannelImplementation (/usr/src/app/node_modules/@grpc/grpc-js/build/src/channel.js:85:48)\n    at new Client (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:37:36)\n    at new ServiceClientImpl (/usr/src/app/node_modules/@grpc/grpc-js/build/src/make-client.js:49:5)\n    at GrpcClient.createStub (/usr/src/app/node_modules/google-gax/build/src/grpc.js:236:22)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","exception":true,"date":"Mon Nov 04 2019 16:38:15 GMT+0000 (Coordinated Universal Time)","process":{"pid":92,"uid":0,"gid":0,"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","version":"v10.16.1","argv":["/usr/local/bin/node","/usr/src/app/index.js"],"memoryUsage":{"rss":117981184,"heapTotal":50601984,"heapUsed":39967664,"external":36527191}},"os":{"loadavg":[2.0703125,1.7734375,1.716796875],"uptime":4105},"trace":[{"column":15,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver-dns.js","function":"Function.getDefaultAuthority","line":253,"method":"getDefaultAuthority","native":false},{"column":32,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/resolver.js","function":"Object.getDefaultAuthority","line":73,"method":"getDefaultAuthority","native":false},{"column":48,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/channel.js","function":"new ChannelImplementation","line":85,"method":null,"native":false},{"column":36,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js","function":"new Client","line":37,"method":null,"native":false},{"column":5,"file":"/usr/src/app/node_modules/@grpc/grpc-js/build/src/make-client.js","function":"new ServiceClientImpl","line":49,"method":null,"native":false},{"column":22,"file":"/usr/src/app/node_modules/google-gax/build/src/grpc.js","function":"GrpcClient.createStub","line":236,"method":"createStub","native":false},{"column":7,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":68,"method":"_tickCallback","native":false}]}
```

**Comment by murgatroid99** [comment]
This looks like a bug in the pubsub library. It looks like it is passing the string `storage.googleapis.com:undefined` to the grpc library, which is not valid.

**Comment by zerefel** [comment]
I wasn't sure how the `storage.googleapis.com:undefined` address was resolved, which is why I assumed it's a grpc issue. Should I take it to the @google-cloud/pubsub team?

**Comment by murgatroid99** [comment]
Yes, as I said it's a bug in the pubsub library, so you should file an issue with that library.
