### ISSUE TITLE
Error: Response closed without headers

### ISSUE THREAD

**Issue by bonedaddy** [grpc/grpc-node#1182]
I have a golang gRPC backend server located at http://xapi-dev.temporal.cloud:9090 and im attempting to communicate with it using nodejs however anytime I start my test client I run into the following error message:

```
{ Error: Response closed without headers
    at Object.onEnd (/home/solidity/Code/RTradeLtd/TxPB/script/status_pb_service.js:52:21)
    at /home/solidity/Code/RTradeLtd/TxPB/script/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24910
    at Array.<anonymous> (/home/solidity/Code/RTradeLtd/TxPB/script/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:5649)
    at e (/home/solidity/Code/RTradeLtd/TxPB/script/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:1531)
    at Timeout._onTimeout (/home/solidity/Code/RTradeLtd/TxPB/script/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:1645)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) code: 2, metadata: e { headersMap: {} } }
```

You should be able to easily reproduce this using either of the following two nodejs scripts:
https://github.com/RTradeLtd/TxPB/blob/screiptbroke/script/sdk.ts or https://github.com/RTradeLtd/TxPB/blob/screiptbroke/script/sdk.js

Not quite sure what I'm doing wrong, but something  appears to be off.

**Comment by murgatroid99** [comment]
That stack trace appears to involve files in the [`@improbable-eng/grpc-web`](https://www.npmjs.com/package/@improbable-eng/grpc-web) package. That package is not associated with this repository, and we are not its maintainers.

That package appears to be specifically made for use in web clients. If you are using Node and not web clients, you may want to try using the `grpc` or `@grpc/grpc-js` package instead. We do maintain those packages.

**Comment by bonedaddy** [comment]
Hmm okay maybe I'm doing this wrong. I tried finding examples on using `grpc` or `grpc/grpc-js` and wasn't able to find anything so I tried extrapolating based off `improbable-eng/rpc-web` but i guess that didnt work.

Do you happen to have links to examples using `grpc` and grpc/grpc-js`

**Comment by murgatroid99** [comment]
There are some examples [here](https://github.com/grpc/grpc/tree/master/examples/node). `@grpc/grpc-js` can be used in place of `grpc` for most basic usage, including everything mentioned in the examples.

**Comment by bonedaddy** [comment]
Awesome thank you very much, i'll close this now.
