### ISSUE TITLE
grpc_tools_node_protoc crashes with ENOENT error

### ISSUE THREAD

**Issue by bonedaddy** [grpc/grpc-node#1205]
### Problem description
Attempting to run `grpc_tools_node_protoc` will always crash

### Reproduction steps
https://github.com/RTradeLtd/TxPB contains the proto files, but I can't even get this far so as for them to be useful.

### Environment

OS:
```shell
$> cat /etc/os-release
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```

Node:  `v12.13.0`
npm: `6.13.1`
grpc: `1.24.0`

### Additional context
```
/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc.js:41
    throw error;
    ^

Error: spawn /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc',
  path: '/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc',
  spawnargs: [
    '--plugin=protoc-gen-grpc=/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/grpc_node_plugin'
  ],
  cmd: '/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc --plugin=protoc-gen-grpc=/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/grpc_node_plugin'
}
```

**Comment by murgatroid99** [comment]
Can you share the full command line you ran `grpc_tools_node_protoc` with?

**Comment by bonedaddy** [comment]
I quite literally ran `grpc_tools_node_protoc`

**Comment by murgatroid99** [comment]
I see that in your Makefile you have several invocations of `protoc` with multiple arguments. `grpc_tools_node_protoc` is just a thin wrapper around `protoc`, except that it also automatically invokes the gRPC Node plugin. So, you should pass it the same arguments that you would pass to `protoc`.

**Comment by bonedaddy** [comment]
I've tried invoking `protoc` with the plugin, and I've tried invoking `grpc_tools_node_protoc` directly, *all* give me the same error which is the error i described in the issue.

**Comment by murgatroid99** [comment]
You may need to pass the `--js_out` and `--grpc_out` arguments as described in [this example](https://github.com/grpc/grpc/tree/master/examples/node/static_codegen), along with the other `protoc` arguments.

**Comment by bonedaddy** [comment]
Yes I'm aware of that example and I have tried that, and it does not work.

**Comment by bonedaddy** [comment]
Yes I'm aware of that example and I have tried that, and it does not work.

**Comment by bonedaddy** [comment]
For example here is the output of running `protoc` with the flags specified in hte example

```
$ protoc --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" -I=pb -I=${GOPATH}/src -I=${GOPATH}/src/github.com/gogo/protobuf/protobuf --js_out=import_style=commonjs,binary:js --ts_out=service=grpc-web:ts --plugin=protoc-gen-grpc-web=build/protoc-gen-grpc-web --grpc-web_out=import_style=commonjs,mode=grpcwebtext:js --grpc_out=js --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` pb/dag.proto

/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc_plugin.js:37
    throw error;
    ^

Error: spawn /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/grpc_node_plugin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/grpc_node_plugin',
  path: '/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/grpc_node_plugin',
  spawnargs: [],
  cmd: '/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/grpc_node_plugin'
}
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
```

**Comment by murgatroid99** [comment]
I agree, it looks like something is going wrong at installation time. `grpc-tools` uses `node-pre-gyp` to install platform-specific executables using an install-time script. Can you share a log of the output of your process for installing `grpc-tools`, and confirm that the executable is still missing after you do that?

**Comment by bonedaddy** [comment]
```shell
$ npm install -g grpc-tools
/home/solidity/.npm_modules/bin/grpc_tools_node_protoc -> /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc.js
/home/solidity/.npm_modules/bin/grpc_tools_node_protoc_plugin -> /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc_plugin.js
+ grpc-tools@1.8.0
updated 1 package in 1.425s
```

```shell
$ ls -l /home/solidity/.npm_modules/bin/grpc_tools_node_protoc_plugin
lrwxrwxrwx 1 solidity solidity 51 Dec  2 18:55 /home/solidity/.npm_modules/bin/grpc_tools_node_protoc_plugin -> ../lib/node_modules/grpc-tools/bin/protoc_plugin.js
```

```shell
$ ls -l /home/solidity/.npm_modules/bin/grpc_tools_node_protoc
lrwxrwxrwx 1 solidity solidity 44 Dec  2 18:55 /home/solidity/.npm_modules/bin/grpc_tools_node_protoc -> ../lib/node_modules/grpc-tools/bin/protoc.js
```
```shell
$ grpc_tools_node_protoc
/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc.js:41
    throw error;
    ^

Error: spawn /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc',
  path: '/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc',
  spawnargs: [
    '--plugin=protoc-gen-grpc=/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/grpc_node_plugin'
  ],
  cmd: '/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc --plugin=protoc-gen-grpc=/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/grpc_node_plugin'
}
```

```shell
$ ls -l /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc
ls: cannot access '/home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc': No such file or directory
```

**Comment by murgatroid99** [comment]
There's the problem: that install log is supposed to have another line that looks like this

```
[grpc-tools] Success: "/tmp/node_modules/grpc-tools/bin/grpc_tools.node" is installed via remote
```

Can you run the installation with the `-dd` flag to get verbose input?

**Comment by bonedaddy** [comment]
Yup here it is
```shell
$> npm install -g grpc-tools -dd
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'grpc-tools',
npm verb cli   '-dd'
npm verb cli ]
npm info using npm@6.13.1
npm info using node@v12.13.0
npm verb npm-session 2aec14c31af60795
npm http fetch GET 304 https://registry.npmjs.org/grpc-tools 949ms (from cache)
npm timing stage:loadCurrentTree Completed in 1062ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 17ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 262ms
npm timing stage:loadIdealTree Completed in 298ms
npm timing stage:generateActionsToTake Completed in 5ms
npm verb correctMkdir /home/solidity/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/solidity/.npm/_locks/staging-962135775948701e.lock for /home/solidity/.npm_modules/lib/node_modules/.staging
npm timing action:extract Completed in 111ms
npm info lifecycle grpc-tools@1.8.0~preuninstall: grpc-tools@1.8.0
npm info lifecycle grpc-tools@1.8.0~uninstall: grpc-tools@1.8.0
npm verb unbuild rmStuff grpc-tools@1.8.0 from /home/solidity/.npm_modules/lib/node_modules
npm info lifecycle grpc-tools@1.8.0~postuninstall: grpc-tools@1.8.0
npm timing action:unbuild Completed in 6ms
npm timing action:remove Completed in 9ms
npm timing action:finalize Completed in 8ms
npm timing action:refresh-package-json Completed in 4ms
npm info lifecycle grpc-tools@1.8.0~preinstall: grpc-tools@1.8.0
npm timing action:preinstall Completed in 0ms
npm info linkStuff grpc-tools@1.8.0
npm verb linkBins [
npm verb linkBins   {
npm verb linkBins     grpc_tools_node_protoc: './bin/protoc.js',
npm verb linkBins     grpc_tools_node_protoc_plugin: './bin/protoc_plugin.js'
npm verb linkBins   },
npm verb linkBins   '/home/solidity/.npm_modules/bin',
npm verb linkBins   true
npm verb linkBins ]
/home/solidity/.npm_modules/bin/grpc_tools_node_protoc_plugin -> /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc_plugin.js
/home/solidity/.npm_modules/bin/grpc_tools_node_protoc -> /home/solidity/.npm_modules/lib/node_modules/grpc-tools/bin/protoc.js
npm timing action:build Completed in 4ms
npm info lifecycle grpc-tools@1.8.0~install: grpc-tools@1.8.0
npm info lifecycle grpc-tools@1.8.0~install: ignored because ignore-scripts is set to true grpc-tools@1.8.0
npm timing action:install Completed in 3ms
npm info lifecycle grpc-tools@1.8.0~postinstall: grpc-tools@1.8.0
npm timing action:postinstall Completed in 0ms
npm verb unlock done using /home/solidity/.npm/_locks/staging-962135775948701e.lock for /home/solidity/.npm_modules/lib/node_modules/.staging
npm timing stage:executeActions Completed in 173ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 1540ms
+ grpc-tools@1.8.0
updated 1 package in 1.542s
npm verb exit [ 0, true ]
npm timing npm Completed in 1736ms
npm info ok 
```

Not sure if this is relevant, but I've adjusted my global npm modules directory with `npm config set prefix ~/.npm_nodules`

**Comment by murgatroid99** [comment]
OK, I believe this is the problem:

```
npm info lifecycle grpc-tools@1.8.0~install: ignored because ignore-scripts is set to true grpc-tools@1.8.0
```

That may be an npm configuration option you have set. As I said, those executables are installed using an install script, so if that script doesn't run the package won't be installed correctly.

**Comment by bonedaddy** [comment]
Ah yes I had set my npm config file to disable install scripts. I have disabled that config and everything seems to be working now thank you very much for the help :rocket: :muscle: 

I'll re-open the issue if i run into this problem again?
