### ISSUE TITLE
PubSub authentication failure when upgrading from 0.7.6 to 0.7.7

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [grpc/grpc-node#1347]
### Problem description
A service of ours (running in GKE) using the `@google-cloud/pubsub` client, version `1.3.0`, recently got updated from 0.7.6 to 0.7.7 of `@grpc/grpc-js`, which is pulled in by `google-gax`. With that update, and _no other changes to the service_ (including other dependencies!), we went from a properly running service to one that _always_ fails to authenticate with this error:
```
Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (mfp=null)
    Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
        at Object.callErrorFromStatus (/usr/lib/node_modules/@sixriver/mfp-communicator/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
        at Object.onReceiveStatus (/usr/lib/node_modules/@sixriver/mfp-communicator/node_modules/@grpc/grpc-js/build/src/client.js:174:52)
        at Object.onReceiveStatus (/usr/lib/node_modules/@sixriver/mfp-communicator/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:340:141)
        at Object.onReceiveStatus (/usr/lib/node_modules/@sixriver/mfp-communicator/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
        at Http2CallStream.outputStatus (/usr/lib/node_modules/@sixriver/mfp-communicator/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
        at Http2CallStream.maybeOutputStatus (/usr/lib/node_modules/@sixriver/mfp-communicator/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
        at Http2CallStream.endCall (/usr/lib/node_modules/@sixriver/mfp-communicator/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
        at Http2CallStream.handleTrailers (/usr/lib/node_modules/@sixriver/mfp-communicator/node_modules/@grpc/grpc-js/build/src/call-stream.js:262:14)
        at ClientHttp2Stream.emit (events.js:198:13)
        at emit (internal/http2/core.js:236:8)
```

This service authenticates by pulling in service account credentials from disk.

### Reproduction steps
- Install `@google-cloud/pubsub` in an app
- Configure the app to authenticate with service credentials
- Try to publish messages to a topic
- Works when `@grpc/grpc-js` is forced to be 0.7.6, fails with above error when it picks up 0.7.7

Working to see if I can generate a more directly testable repro setup.

### Environment
 - OS name, version and architecture: Linux
 - Node version: 10.16.2
 - Node installation method: Debian package from nodesource.com
 - If applicable, compiler version: Unknown
 - Package name and version `@grpc/grpc-js` version 0.7.7 via`google-gax` via `@google-cloud/pubsub`

### Additional context

FYI @tonygaetani if you can add any additional context or logs you captured would be useful

**Comment by mgabeler-lee-6rs** [comment]
https://github.com/mgabeler-lee-6rs/grpc-node-issue-1347 has a minimal version of the code our app uses that fails this way, but I'm not reproducing the failure there, so working to see what the minimal subset of our app I need to add there (or remove from our app) to either reproduce the failure (or make it go away in the app).

**Comment by murgatroid99** [comment]
I think I have a fix in #1349. Would you be able to patch that into your client that's breaking to see if that fixes the problem?

**Comment by mgabeler-lee-6rs** [comment]
I'll see if we can test that out. Thanks for looking into this so fast!

**Comment by murgatroid99** [comment]
I just published grpc-js version 0.7.9 with that possible fix. That might make it easier for you to try it out.

**Comment by mgabeler-lee-6rs** [comment]
That will in fact make it _much_ easier, yes :grinning:

**Comment by mgabeler-lee-6rs** [comment]
I've confirmed that 0.7.9 fixes this issue for us, so closing this ticket, many thanks again :grinning:
