### ISSUE TITLE
cannot build on FreeBSD

### ISSUE THREAD

**Issue by drook** [grpc/grpc-node#136]
(in case you will think "some guy just keeps posting about my app not building on abandonware" - I really have no live/decent Linuxes there, so please don't think it's some kind of trolling - it's not)

gcc:
````GCC
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc5/gcc/x86_64-portbld-freebsd11.0/5.4.0/lto-wrapper
Target: x86_64-portbld-freebsd11.0
Configured with: /wrkdirs/usr/ports/lang/gcc/work/gcc-5.4.0/configure --disable-bootstrap --disable-nls --enable-gnu-indirect-function --libdir=/usr/local/lib/gcc5 --libexecdir=/usr/local/libexec/gcc5 --program-suffix=5 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc5/include/c++/ --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --with-ecj-jar=/usr/local/share/java/ecj-4.5.jar --enable-languages=c,c++,objc,fortran,java --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/gcc5 --build=x86_64-portbld-freebsd11.0
Thread model: posix
gcc version 5.4.0 (FreeBSD Ports Collection)
````

````build log
> npm install grpc

> grpc@1.8.0 install /usr/home/emz/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v51-freebsd-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@7.8.0 (node-v51 ABI, unknown) (falling back to source compile with node-gyp)
gmake: вход в каталог «/usr/home/emz/node_modules/grpc/build»
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
[...]
  CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/support/tmpfile_windows.o
  CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/support/wrap_memcpy.o
  AR(target) Release/obj.target/libgpr.a
  COPY Release/libgpr.a
  CXX(target) Release/obj.target/grpc_node/ext/byte_buffer.o
c++: error: unknown argument: '-zdefs'
gmake: *** [grpc_node.target.mk:158: Release/obj.target/grpc_node/ext/byte_buffer.o] Ошибка 1
gmake: выход из каталога «/usr/home/emz/node_modules/grpc/build»
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System FreeBSD 11.0-RELEASE-p5
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/usr/home/emz/node_modules/grpc/src/node/extension_binary/node-v51-freebsd-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/usr/home/emz/node_modules/grpc/src/node/extension_binary/node-v51-freebsd-x64-unknown"
gyp ERR! cwd /usr/home/emz/node_modules/grpc
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/usr/home/emz/node_modules/grpc/src/node/extension_binary/node-v51-freebsd-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/usr/home/emz/node_modules/grpc/src/node/extension_binary/node-v51-freebsd-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/home/emz/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System FreeBSD 11.0-RELEASE-p5
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/home/emz/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /usr/home/emz/node_modules/grpc
node-pre-gyp ERR! node -v v7.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/usr/home/emz/node_modules/grpc/src/node/extension_binary/node-v51-freebsd-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/usr/home/emz/node_modules/grpc/src/node/extension_binary/node-v51-freebsd-x64-unknown' (1)
npm WARN enoent ENOENT: no such file or directory, open '/usr/home/emz/package.json'
npm WARN emz No description
npm WARN emz No repository field.
npm WARN emz No README data
npm WARN emz No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.8.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.8.0 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emz/.npm/_logs/2017-12-21T17_56_18_305Z-debug.log
````

**Comment by Techwolf12** [comment]
Same issue here. Glad to see it is getting a lot of attention from the maintainers 👍

**Comment by Techwolf12** [comment]
Right, already seemed to have gcc installed. It works now like this:

`env LINK=gcc6 CC=gcc6 CXX=g++6 LINKXX=g++6 npm install grpc`

If you use pkg, you can install lang/gcc49, just replace the 6 with 49 in the command list.

**Comment by eatonphil** [comment]
Delete the line that includes `-zdef` in the appropriate file relative to the version (and package manager) you're installing for a quick fix. For me on version 1.9.0, the file was `~/.cache/yarn/v1/npm-grpc-1.9.0-99ca91c7dddc158da1d7edc4f7e09971a8b68a84/binding.gyp`

**Comment by przemika** [comment]
I confirm it's binding.gyp file. 
I'm not a champion of gyp files but I think it should be something like this
```
"conditions": [
        ['OS=="freebsd"', {
          'cflags': [
          '-pthread',
          '-Wno-error=deprecated-declarations'
      ],
        }],
        ['OS!="freebsd"', {
          'cflags': [
          '-pthread',
          '-zdefs',
          '-Wno-error=deprecated-declarations'
        }],
      ],

**Comment by nicolasnoble** [comment]
We've removed zdefs.
