### ISSUE TITLE
grpc-tools install failed.

### ISSUE THREAD

**Issue by engnakagawa** [grpc/grpc-node#1377]
### Problem description
grpc-tools install failed.

### Reproduction steps
```
$ docker run -it --rm -w /app node yarn add grpc-tools
yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /app/node_modules/grpc-tools: Command failed.
Exit code: 1
Command: node-pre-gyp install
Arguments: 
Directory: /app/node_modules/grpc-tools
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@13.13.0 | linux | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp info check checked for "/app/node_modules/grpc-tools/bin/grpc_tools.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.8.1/linux-x64.tar.gz
node-pre-gyp http 200 https://node-precompiled-binaries.grpc.io/grpc-tools/v1.8.1/linux-x64.tar.gz
node-pre-gyp info install unpacking bin/
node-pre-gyp info install unpacking bin/grpc_node_plugin
node-pre-gyp info install unpacking bin/protoc
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: bad download
node-pre-gyp ERR! stack     at Unpack.afterTarball (/app/node_modules/node-pre-gyp/lib/install.js:100:46)
node-pre-gyp ERR! stack     at Unpack.emit (events.js:315:20)
node-pre-gyp ERR! stack     at Unpack.[maybeClose] (/app/node_modules/tar/lib/unpack.js:171:12)
node-pre-gyp ERR! stack     at Unpack.[unpend] (/app/node_modules/tar/lib/unpack.js:394:21)
node-pre-gyp ERR! stack     at /app/node_modules/tar/lib/unpack.js:308:46
node-pre-gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:159:23)
node-pre-gyp ERR! System Linux 4.19.76-linuxkit
node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /app/node_modules/grpc-tools
node-pre-gyp ERR! node -v v13.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
bad download
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Environment
 - OSVersion: macOS Catalina ```$ uname -v #> Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64```
 - Node version: ```$ docker run -it --rm -w /app node node -v #> v14.0.0```
 - Node installation method: docker official image
 - Package name and version: grpc-tools@1.8.1

### Additional context
node:lts → success.
node:latest → failed.

**Comment by tweenietomatoes** [comment]
Windows 10 x64
NodeJS 14 Failed.

**Comment by Alabate** [comment]
Maybe a duplicate of https://github.com/grpc/grpc-node/issues/1362

**Comment by engnakagawa** [comment]
I confirmed that it was supported. Thank you! <3

```
~ took 36s 
➜ docker run -it --rm node:14.9.0 yarn add grpc-tools
Unable to find image 'node:14.9.0' locally
14.9.0: Pulling from library/node
Digest: sha256:6b7a33663630d4ae48bd369726607488c25c37a42702644ed8e2e9fd483306ee
Status: Downloaded newer image for node:14.9.0
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 63 new dependencies.
info Direct dependencies
└─ grpc-tools@1.9.1
info All dependencies
├─ abbrev@1.1.1
├─ ansi-regex@2.1.1
├─ aproba@1.2.0
├─ are-we-there-yet@1.1.5
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.11
├─ chownr@1.1.4
├─ code-point-at@1.1.0
├─ concat-map@0.0.1
├─ console-control-strings@1.1.0
├─ core-util-is@1.0.2
├─ debug@3.2.6
├─ deep-extend@0.6.0
├─ delegates@1.0.0
├─ detect-libc@1.0.3
├─ fs-minipass@1.2.7
├─ fs.realpath@1.0.0
├─ gauge@2.7.4
├─ glob@7.1.6
├─ grpc-tools@1.9.1
├─ has-unicode@2.0.1
├─ iconv-lite@0.4.24
├─ ignore-walk@3.0.3
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ ini@1.3.5
├─ is-fullwidth-code-point@1.0.0
├─ isarray@1.0.0
├─ minimist@1.2.5
├─ minipass@2.9.0
├─ minizlib@1.3.3
├─ mkdirp@0.5.5
├─ ms@2.1.2
├─ needle@2.5.0
├─ node-pre-gyp@0.15.0
├─ nopt@4.0.3
├─ npm-bundled@1.1.1
├─ npm-packlist@1.4.8
├─ npmlog@4.1.2
├─ number-is-nan@1.0.1
├─ object-assign@4.1.1
├─ os-homedir@1.0.2
├─ os-tmpdir@1.0.2
├─ osenv@0.1.5
├─ path-is-absolute@1.0.1
├─ process-nextick-args@2.0.1
├─ rc@1.2.8
├─ readable-stream@2.3.7
├─ rimraf@2.7.1
├─ safe-buffer@5.1.2
├─ safer-buffer@2.1.2
├─ sax@1.2.4
├─ semver@5.7.1
├─ set-blocking@2.0.0
├─ signal-exit@3.0.3
├─ string_decoder@1.1.1
├─ string-width@1.0.2
├─ strip-ansi@3.0.1
├─ strip-json-comments@2.0.1
├─ tar@4.4.13
├─ util-deprecate@1.0.2
├─ wide-align@1.1.3
└─ yallist@3.1.1
Done in 4.56s.
```
