### ISSUE TITLE
Yarn Installation Failure on Node 12, but not Node 10

### ISSUE THREAD

**Issue by ecbrodie** [grpc/grpc-node#1392]
### Problem description

When running `yarn install` on a project that uses `grpc` (for me, as a downstream dependency to `firebase`), I get an installation failure while using Node 12, but not while using Node 10. The failure appears to occur in yarn during the "Building fresh packages stage" --> "grpc". Is there a Node versioning incompatibility issue?

### Reproduction steps

I ran `yarn install` while the project had Node 12.16.1 installed via nvm and I got the error message (see below). When I switched to Node 10.20.1, the `yarn` install command succeeded without any error.

Assume that this error can be reproduced on a project that had its `node_modules` directory deleted and `yarn cache clean` was already executed.

I am not sure if the problem is specifically related to `grpc-node` or something else (perhaps `node-pre-gyp`). I really don't know. I'm happy to be pointed in another direction if necessary.

### Environment

 - OS name, version and architecture: Mac OS 10.15.4
 - Node version 12.16.2
 - Node installation method: nvm
 - grpc 1.20.0

### Additional context

Here's the error (a large quantity of lines starting with `CXX(target)` were omitted, I can add them in if needed):

```
error /Users/evanbrodie/git/myProject/node_modules/grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: /Users/evanbrodie/git/myProject/node_modules/grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.16.2 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/evanbrodie/git/myProject/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-darwin-x64-unknown.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.20.0 and node@12.16.2 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-darwin-x64-unknown.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.16.2 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.16.2 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/evanbrodie/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/evanbrodie/git/myProject/node_modules/grpc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/evanbrodie/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/evanbrodie/Library/Caches/node-gyp/12.16.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/evanbrodie/Library/Caches/node-gyp/12.16.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/evanbrodie/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/evanbrodie/Library/Caches/node-gyp/12.16.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/evanbrodie/git/myProject/node_modules/grpc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.16.2 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target)...
  ...
  ../ext/channel.cc:292:56: error: too few arguments to function call, expected 2, have 1
  int try_to_connect = (int)info[0]->Equals(Nan::True());
                            ~~~~~~~~~~~~~~~            ^
/Users/evanbrodie/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2712:3: note: 'Equals' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> Equals(Local<Context> context,
  ^
/Users/evanbrodie/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
1 error generated.
make: *** [Release/obj.target/grpc_node/ext/channel.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/evanbrodie/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/evanbrodie/.nvm/versions/node/v12.16.2/bin/node" "/Users/evanbrodie/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/evanbrodie/git/myProject/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/evanbrodie/git/myProject/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/evanbrodie/git/myProject/node_modules/grpc
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/evanbrodie/.nvm/versions/node/v12.16.2/bin/node /Users/evanbrodie/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/evanbrodie/git/myProject/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/evanbrodie/git/myProject/node_modules/grpc/src/node/extension_binary/node-v72-darwin-x64-unknown --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/evanbrodie/git/myProject/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.4.0
node-pre-gyp ERR! command "/Users/evanbrodie/.nvm/versions/node/v12.16.2/bin/node" "/Users/evanbrodie/git/myProject/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/evanbrodie/git/myProject/node_modules/grpc
node-pre-gyp ERR! node -v v12.16.2
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
```

And here's my `package.json` (yes it's an Expo project):

```
{
  "dependencies": {
    "@expo/vector-icons": "^9.0.0",
    "@types/expo__vector-icons": "^9.0.1",
    "@types/uuid": "^3.4.4",
    "expo": "^34.0.1",
    "firebase": "^5.9.4",
    "native-base": "^2.11.0",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@types/react": "^16.8",
    "babel-preset-expo": "6.0.0",
    "jest-expo": "^34.0.1",
    "prettier": "1.18.2",
    "typescript": "^3.5.3"
  }
}
```

Thank you. 🙏

**Comment by ecbrodie** [comment]
Siiiiiigghhhh....It was just a Firebase issue: https://github.com/firebase/firebase-js-sdk/issues/1738

Upgrading to the latest Firebase version solved the problem. No more Node 12 installation errors.

Closing now...
