### ISSUE TITLE
grpc-js: grpc.Server can not bind port "0.0.0.0:50051"

### ISSUE THREAD

**Issue by leonschun** [grpc/grpc-node#1416]
### Problem description
grpc.Server can not bind port "0.0.0.0:50051" in grpc-js, but it can in  grpc-node.

### Reproduction steps
In grpc-js.
![image](https://user-images.githubusercontent.com/3643627/81460945-243c0500-91db-11ea-9054-c84cdc0eb7fe.png)

In grpc-node.
![image](https://user-images.githubusercontent.com/3643627/81461023-b17f5980-91db-11ea-8b99-f5b229ef3507.png)

**Comment by murgatroid99** [comment]
In your test, something is definitely bound to that port, because that something is responding with an `UNIMPLEMENTED` error. Can you try the test again and make sure that no other servers are running on that port.

**Comment by anchel** [comment]
the same problem on windows os. it works ok on linux os

**Comment by LeonsChun** [comment]
@murgatroid99 grpc-js works fine with "localhost:50051" but "0.0.0.0:50051". I'm very sure that grpc.Server from above code bound the port 50051.

**Comment by murgatroid99** [comment]
Sorry, you're saying that if you replace `0.0.0.0` with `localhost` in that test, the server responds differently?

**Comment by LeonsChun** [comment]
@murgatroid99 Yes.

**Comment by murgatroid99** [comment]
Can you provide a complete piece of code that reproduces this problem? Also, please state what operating system you are using, and the versions of Node and grpc-js.

**Comment by LeonsChun** [comment]
Code in [demo.zip](https://github.com/grpc/grpc-node/files/4613237/demo.zip)
node: v12.16.2
os: win10 enterprise ltsc 1809

**Comment by murgatroid99** [comment]
When I run that demo on Node 12.16.2 on Windows 10 it outputs "grpc responed".

Can you maybe just reboot your computer and run the test again?

**Comment by LeonsChun** [comment]
I just tried, but not work.

**Comment by murgatroid99** [comment]
I added some more trace output to grpc-js to help understand this problem. Can you update your dependencies to pick up grpc-js version 1.0.4 and run the test again with the environment variables `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG` and share the output?

**Comment by tweenietomatoes** [comment]
did you try this:
```
 server.bindAsync('0.0.0.0:50051', grpc.ServerCredentials.createInsecure(), starter)
    function starter() {
      server.start()
    }
```

**Comment by LeonsChun** [comment]
Executing task: npm run start <


demo@1.0.0 start C:\Inventory\Desktop\demo
node ./build/app.js

2020-05-22T06:16:05.454Z | dns_resolver | Resolver constructed for target dns:0.0.0.0:50051
2020-05-22T06:16:05.457Z | dns_resolver | Resolution update requested for target dns:0.0.0.0:50051
2020-05-22T06:16:05.457Z | dns_resolver | Returning IP address for target dns:0.0.0.0:50051
2020-05-22T06:16:05.458Z | server | Attempting to bind 0.0.0.0:50051
2020-05-22T06:16:05.461Z | server | Successfully bound 0.0.0.0:50051
2020-05-22T06:16:05.462Z | resolving_load_balancer | dns:localhost:50051 IDLE -> IDLE
2020-05-22T06:16:05.462Z | connectivity_state | dns:localhost:50051 IDLE -> IDLE
2020-05-22T06:16:05.462Z | dns_resolver | Resolver constructed for target dns:localhost:50051
2020-05-22T06:16:05.463Z | channel | dns:localhost:50051 createCall [0] method="/DemoService/a", deadline=Infinity
2020-05-22T06:16:05.464Z | call_stream | [0] Sending metadata
2020-05-22T06:16:05.464Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-05-22T06:16:05.465Z | call_stream | [0] write() called with message of length 0
2020-05-22T06:16:05.465Z | call_stream | [0] end() called
2020-05-22T06:16:05.466Z | call_stream | [0] deferring writing data chunk of length 5
2020-05-22T06:16:05.466Z | dns_resolver | Resolution update requested for target dns:localhost:50051
2020-05-22T06:16:05.467Z | resolving_load_balancer | dns:localhost:50051 IDLE -> CONNECTING
2020-05-22T06:16:05.467Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-05-22T06:16:05.467Z | connectivity_state | dns:localhost:50051 IDLE -> CONNECTING
2020-05-22T06:16:05.467Z | resolving_load_balancer | dns:localhost:50051 CONNECTING -> CONNECTING
2020-05-22T06:16:05.467Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-05-22T06:16:05.468Z | connectivity_state | dns:localhost:50051 CONNECTING -> CONNECTING
2020-05-22T06:16:05.468Z | dns_resolver | Resolved addresses for target dns:localhost:50051: [::1:50051,127.0.0.1:50051]
2020-05-22T06:16:05.469Z | pick_first | Connect to address list ::1:50051,127.0.0.1:50051
2020-05-22T06:16:05.470Z | subchannel | ::1:50051 refcount 0 -> 1
2020-05-22T06:16:05.470Z | subchannel | 127.0.0.1:50051 refcount 0 -> 1
2020-05-22T06:16:05.470Z | subchannel | ::1:50051 refcount 1 -> 2
2020-05-22T06:16:05.470Z | subchannel | 127.0.0.1:50051 refcount 1 -> 2
2020-05-22T06:16:05.471Z | pick_first | Start connecting to subchannel with address ::1:50051
2020-05-22T06:16:05.471Z | pick_first | IDLE -> CONNECTING
2020-05-22T06:16:05.471Z | resolving_load_balancer | dns:localhost:50051 CONNECTING -> CONNECTING
2020-05-22T06:16:05.471Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-05-22T06:16:05.471Z | connectivity_state | dns:localhost:50051 CONNECTING -> CONNECTING
2020-05-22T06:16:05.472Z | subchannel | ::1:50051 IDLE -> CONNECTING
2020-05-22T06:16:05.475Z | pick_first | CONNECTING -> CONNECTING
2020-05-22T06:16:05.477Z | resolving_load_balancer | dns:localhost:50051 CONNECTING -> CONNECTING
2020-05-22T06:16:05.478Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-05-22T06:16:05.478Z | connectivity_state | dns:localhost:50051 CONNECTING -> CONNECTING
2020-05-22T06:16:05.478Z | subchannel | 127.0.0.1:50051 IDLE -> CONNECTING
2020-05-22T06:16:05.479Z | pick_first | CONNECTING -> CONNECTING
2020-05-22T06:16:05.479Z | resolving_load_balancer | dns:localhost:50051 CONNECTING -> CONNECTING
2020-05-22T06:16:05.480Z | channel | Pick result: QUEUE subchannel: undefined status: undefined undefined
2020-05-22T06:16:05.480Z | connectivity_state | dns:localhost:50051 CONNECTING -> CONNECTING
2020-05-22T06:16:05.484Z | subchannel | 127.0.0.1:50051 CONNECTING -> READY
2020-05-22T06:16:05.486Z | pick_first | Pick subchannel with address 127.0.0.1:50051
2020-05-22T06:16:05.487Z | pick_first | CONNECTING -> READY
2020-05-22T06:16:05.487Z | resolving_load_balancer | dns:localhost:50051 CONNECTING -> READY
2020-05-22T06:16:05.488Z | channel | Pick result: COMPLETE subchannel: 127.0.0.1:50051 status: undefined undefined
2020-05-22T06:16:05.488Z | connectivity_state | dns:localhost:50051 CONNECTING -> READY
2020-05-22T06:16:05.489Z | subchannel | 127.0.0.1:50051 refcount 2 -> 3
2020-05-22T06:16:05.489Z | subchannel | ::1:50051 refcount 2 -> 1
2020-05-22T06:16:05.490Z | subchannel | 127.0.0.1:50051 refcount 3 -> 2
2020-05-22T06:16:05.492Z | subchannel | Starting stream with headers
                grpc-accept-encoding: identity,deflate,gzip
                accept-encoding: identity,gzip
                :authority: localhost
                user-agent: grpc-node-js/1.0.4
                content-type: application/grpc
                :method: POST
                :path: /DemoService/a
                te: trailers

2020-05-22T06:16:05.492Z | call_stream | [0] attachHttp2Stream from subchannel 127.0.0.1:50051
2020-05-22T06:16:05.492Z | subchannel | 127.0.0.1:50051 callRefcount 0 -> 1
2020-05-22T06:16:05.493Z | call_stream | [0] sending data chunk of length 5 (deferred)
2020-05-22T06:16:05.493Z | call_stream | [0] calling end() on HTTP/2 stream
2020-05-22T06:16:05.495Z | call_stream | [0] Received server headers:
                :status: 200
                content-type: application/grpc
                grpc-status: 12
                grpc-message: RPC method not implemented /DemoService/a

2020-05-22T06:16:05.496Z | call_stream | [0] Received server trailers:
                :status: 200
                content-type: application/grpc
                grpc-status: 12
                grpc-message: RPC method not implemented /DemoService/a

2020-05-22T06:16:05.497Z | call_stream | [0] received status code 12 from server
2020-05-22T06:16:05.497Z | call_stream | [0] received status details string "RPC method not implemented /DemoService/a" from server
2020-05-22T06:16:05.498Z | call_stream | [0] ended with status: code=12 details="RPC method not implemented /DemoService/a"
Error: 12 UNIMPLEMENTED: RPC method not implemented /DemoService/a
    at Object.callErrorFromStatus (C:\Inventory\Desktop\demo\node_modules\@grpc\grpc-js\build\src\call.js:30:26)
    at Object.onReceiveStatus (C:\Inventory\Desktop\demo\node_modules\@grpc\grpc-js\build\src\client.js:175:52)
    at Object.onReceiveStatus (C:\Inventory\Desktop\demo\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:341:141)
    at Object.onReceiveStatus (C:\Inventory\Desktop\demo\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (C:\Inventory\Desktop\demo\node_modules\@grpc\grpc-js\build\src\call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (C:\Inventory\Desktop\demo\node_modules\@grpc\grpc-js\build\src\call-stream.js:155:22)
    at Http2CallStream.endCall (C:\Inventory\Desktop\demo\node_modules\@grpc\grpc-js\build\src\call-stream.js:141:18)
    at Http2CallStream.handleTrailers (C:\Inventory\Desktop\demo\node_modules\@grpc\grpc-js\build\src\call-stream.js:266:14)
    at ClientHttp2Stream.<anonymous> (C:\Inventory\Desktop\demo\node_modules\@grpc\grpc-js\build\src\call-stream.js:315:26)
    at ClientHttp2Stream.emit (events.js:310:20) {
  code: 12,
  details: 'RPC method not implemented /DemoService/a',
  metadata: Metadata {
    internalRepr: Map { 'content-type' => [Array] },
    options: {}
  }
}
2020-05-22T06:16:05.504Z | subchannel | 127.0.0.1:50051 callRefcount 1 -> 0
2020-05-22T06:16:05.506Z | call_stream | [0] HTTP/2 stream closed with code 8
2020-05-22T06:16:05.518Z | pick_first | Connect to address list ::1:50051,127.0.0.1:50051
2020-05-22T06:16:05.518Z | subchannel | ::1:50051 refcount 1 -> 2
2020-05-22T06:16:05.518Z | subchannel | 127.0.0.1:50051 refcount 2 -> 3
2020-05-22T06:16:05.519Z | pick_first | Pick subchannel with address 127.0.0.1:50051
2020-05-22T06:16:05.519Z | subchannel | 127.0.0.1:50051 refcount 3 -> 2
2020-05-22T06:16:05.520Z | pick_first | READY -> READY
2020-05-22T06:16:05.521Z | resolving_load_balancer | dns:localhost:50051 READY -> READY
2020-05-22T06:16:05.521Z | connectivity_state | dns:localhost:50051 READY -> READY
2020-05-22T06:16:05.521Z | subchannel | 127.0.0.1:50051 refcount 2 -> 3
2020-05-22T06:16:05.522Z | subchannel | ::1:50051 refcount 2 -> 1
2020-05-22T06:16:05.522Z | subchannel | 127.0.0.1:50051 refcount 3 -> 2
2020-05-22T06:16:06.484Z | subchannel | ::1:50051 connection closed with error connect ECONNREFUSED ::1:50051
2020-05-22T06:16:06.485Z | subchannel | ::1:50051 CONNECTING -> TRANSIENT_FAILURE
2020-05-22T06:16:15.470Z | subchannel | ::1:50051 refcount 1 -> 0

**Comment by murgatroid99** [comment]
That log shows that the client is not connecting to the server that is running in that process. It is connecting to a different server. If it did connect to that server, there would be a log line that starts with "Received call to method", plus a couple of other logs.

Here's a really simple way to test that: comment out the line that binds and starts the server, and run the test again.

**Comment by LeonsChun** [comment]
I found a WXDrive.exe is using the port 50051. Then I killed the WXDrive.exe and the demo worked fine.

Why grpc did not tell me that another exe was using that port?

Then I do 2 tests. 

Test 1:
Start a grpc-js server bind 0.0.0.0:50051.  After the grpc-js server started, start a grpc-node server bind 0.0.0.0:50051. Create a client of grpc-js and a client of grpc-node, both with localhost:50051. Then both clients request and both servers get one request.

Test 2:
Start the grpc-node server first, then the grpc-js server. Create two new clients like above and request. Only grpc-node server get two requests, grpc-js get none.

Why grpc-node have a high priority then grpc-js?

**Comment by murgatroid99** [comment]
I don't know why it's doing that. According to the log, the underlying Node `http2` server is telling `grpc-js` that it has successfully bound the port. As for grpc-node taking precedence, it has a very different code path for binding ports, so it may be doing something different, but I don't know what.

**Comment by mohan570** [comment]
Hi Murgatroid99,

Am having issue while using dialogflow node js client with grpc/grpc-js ,

find below the error

ERROR: Error: Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443
at Http2CallStream. (API\node_modules\dialogflow\node_modules@grpc\grpc-js\build\src\client.js:102:45)
at Http2CallStream.emit (events.js:322:22)
at Http2CallStream.endCall (API\node_modules\dialogflow\node_modules@grpc\grpc-js\build\src\call-stream.js:74:18)
at API\node_modules\dialogflow\node_modules@grpc\grpc-js\build\src\call-stream.js:355:18
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
code: 'ECONNREFUSED',
details: 'Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443',
metadata: Metadata { internalRepr: Map {} }


FYI, in some time its working and some time we got the above error.


Regards,
Mohan A

**Comment by Achyut198** [comment]
Getting same issue with fastapi, 
With all port getting error in windows, but in mac and linux running, 

Can anyone provide a solid solution for this
