### ISSUE TITLE
"Error: 14 UNAVAILABLE: Stream refused by server"

### ISSUE THREAD

**Issue by nnthuanegany** [grpc/grpc-node#1418]
### Problem description
![image](https://user-images.githubusercontent.com/40480004/81488246-8440b300-9290-11ea-9617-6ac8a2047f7f.png)

```proto3
syntax = "proto3";

package messager;

service Messager {
  rpc getInfo(Request) returns (Reply){}
}

message Reply {
  string raw = 1;
}

message Request {
  string raw = 1;
}
```

```js
// server.js
const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');
const path = require('path')

let packageDefinition = protoLoader.loadSync(
    path.join(__dirname, 'messager.proto'),
    {
        keepCase: true,
        longs: String,
        enums: String,
        defaults: true,
        oneofs: true
    });
let messager = grpc.loadPackageDefinition(packageDefinition).messager;
let server = new grpc.Server();
server.addService(messager.Messager.service, {
    getInfo: (call, callback) => {
        callback(null, { raw: 'This is server' });
    }
});
server.bindAsync('0.0.0.0:3000', grpc.ServerCredentials.createInsecure(), (err, port) => {
    if (err) {
        console.log(err);
    } else {
        console.log('GRPC server running on port: ' + port);
    }
});
```
```js
// client.js
const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');
const path = require('path')

let packageDefinition = protoLoader.loadSync(
    path.join(__dirname, 'messager.proto'),
    {
        keepCase: true,
        longs: String,
        enums: String,
        defaults: true,
        oneofs: true
    });
let messager = grpc.loadPackageDefinition(packageDefinition).messager;
let client = new messager.Messager('0.0.0.0:3000', grpc.credentials.createInsecure());
client.getInfo({}, (err, reply) => {
    if (err) {
        console.log(err);
    } else {
        console.log(reply);
    }
})
```
### Environment
 - OS name: Ubuntu 19.10, version and architecture: [Linux Ubuntu 19.10 amd64]
 - Node version: v12.16.1
 - Package name and version: "@grpc/grpc-js": "^1.0.3", "@grpc/proto-loader": "^0.5.4", 

### Full Error
````bash
Error: 14 UNAVAILABLE: Stream refused by server
    at Object.callErrorFromStatus (/Research/grpcjs/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/Research/grpcjs/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/Research/grpcjs/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/Research/grpcjs/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/Research/grpcjs/node_modules/@grpc/grpc-js/build/src/call-stream.js:115:74)
    at Http2CallStream.maybeOutputStatus (/Research/grpcjs/node_modules/@grpc/grpc-js/build/src/call-stream.js:154:22)
    at Http2CallStream.endCall (/Research/grpcjs/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at ClientHttp2Stream.<anonymous> (/Research/grpcjs/node_modules/@grpc/grpc-js/build/src/call-stream.js:396:22)
    at ClientHttp2Stream.emit (events.js:311:20)
    at emitCloseNT (internal/streams/destroy.js:69:8) {
  code: 14,
  details: 'Stream refused by server',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}
````

**Comment by dooleyb1** [comment]
Still getting this issue, how did you resolve?

**Comment by dooleyb1** [comment]
Resolved personally by updating node modules FROM:

```
    "firebase-admin": "^8.7.0",
    "googleapis": "^42.0.0",
```

TO:

```
    "firebase-admin": "^9.1.1",
    "googleapis": "^59.0.0",
```

**Comment by nnthuanegany** [comment]
Hello @ dooleyb1
This issue because of the "server" instance calls server.start(); outside the callback when bindAsync.

So just starting the server in the callback solves the problem. It looks like this

```js
//server.js
server.bindAsync(`${config.address}:${config.port}`, grpc.ServerCredentials.createInsecure(),  (err, port) => {
  if (err) {
    logger.log(err);
    process.exit(1);
  } else {
    server.start(); //here
    logger.info(`Address: ${config.address}`);
    logger.info(`Port: ${port}`);
  }
});
```

**Comment by lwmxiaobei** [comment]
I also encountered it, it was useless if I followed your way

**Comment by nnthuanegany** [comment]
Hi @lwmxiaobei

https://www.npmjs.com/package/grpc - "This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead."

I think this package has many issues, you can use https://www.npmjs.com/package/@grpc/grpc-js instead, and good luck.

Currently, I no longer use the gRPC library on NodeJS.

**Comment by nnthuanegany** [comment]
Hi @lwmxiaobei, maybe your case is a different problem than mine. I also read some similar problems caused by setup "credentials"
