### ISSUE TITLE
Error: 14 UNAVAILABLE: TCP Read failed

### ISSUE THREAD

**Issue by AbhijitGite4Git** [grpc/grpc-node#1432]
### Problem description
The problem happens on a regular basis when the client is ideal after connecting to GRPC sever
### Reproduction steps
This error occurs randomly after connecting to grpc server when client is ideal for some time 

### Environment
 - MacOS 10.15.4 (19E287)
 - 12.14.1
 - Node installation method nvm
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 -  grpc/grpc-js": "^1.0.3

### Additional context
Error: 14 UNAVAILABLE: TCP Read failed
    at Object.exports.createStatusError (/Users/grpc-service/project/tracker-grpc/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/Users/grpc-service/project/tracker-grpc/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/Users/grpc-service/project/tracker-grpc/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/grpc-service/project/tracker-grpc/node_modules/grpc/src/client_interceptors.js:1311:15)
    at InterceptingListener._callNext (/Users/grpc-service/project/tracker-grpc/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/grpc-service/project/tracker-grpc/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/grpc-service/project/tracker-grpc/node_modules/grpc/src/client_interceptors.js:1127:18 {
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'TCP Read failed'
}

**Comment by ming2020** [comment]
Try reducing `grpc` to 1.22.2

**Comment by fooSynaptic** [comment]
same issue after 23days running on  production env .

**Comment by vKolerts** [comment]
same issue

**Comment by vKolerts** [comment]
I found solution at http://www.longfan.me/post/devops/2020-07-09
I add at ClientOptions
`transport: Transport.GRPC,
  options: {
   keepalive: {
      keepaliveTimeMs: 900,
      keepalivePermitWithoutCalls: 1,
      http2MaxPingsWithoutData: 0,
    },
   ...` and it solve this issue
