### ISSUE TITLE
node client connecting to dart server with self signed certificate fail 14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by u007** [grpc/grpc-node#1451]
### Problem description
ive generated required certificate with CA, server and client.
and also removed client.key password in order to have client.key working with js because i think the nodejs client cannot support password protected key.
I've a working dart server and client for grpc.
but when i tried to connect even via localhost, it failed with 14 UNAVAILABLE.

### Reproduction steps

SSL generation
```
openssl genrsa -passout pass:111 -des3 -out ssl/ca.key 4096
openssl req -passin pass:111 -new -x509 -days 3650 -key ssl/ca.key -out ssl/ca.crt -subj  "/C=SG/ST=Singapore/L=Singapore/O=Example Ltd/OU=IT/CN=grpc.example.com"

openssl genrsa -passout pass:111 -des3 -out ssl/server.key 4096
openssl req -passin pass:111 -new -key ssl/server.key -out ssl/server.csr -subj "/C=SG/ST=Singapore/L=Singapore/O=Example Ltd/OU=Server/CN=grpc.example.com"

openssl x509 -req -passin pass:111 -days 3650 -in ssl/server.csr -CA ssl/ca.crt -CAkey ssl/ca.key -set_serial 01 -out ssl/server.crt

openssl genrsa -passout pass:111 -des3 -out ssl/client.key 4096

# remove password from client.key cox js side cannot specify password!
cp ssl/client.key ssl/client.key.org
openssl rsa -in ssl/client.key.org -out ssl/client.key

openssl req -passin pass:111 -new -key ssl/client.key -out ssl/client.csr -subj "/C=SG/ST=Singapore/L=Singapore/O=Example Ltd/OU=Client/CN=grpc.example.com"

openssl x509 -passin pass:111 -req -days 3650 -in ssl/client.csr -CA ssl/ca.crt -CAkey ssl/ca.key -set_serial 01 -out ssl/client.crt

# test
openssl x509 -noout -text -in ssl/client.crt
```

dart server tls initialization
```
await server.serve(
        port: port,
        security: grpc.ServerTlsCredentials(
            certificate: await File('ssl/server.crt').readAsBytes(),
            privateKey: await File('ssl/server.key').readAsBytes(),
            privateKeyPassword: '111'));
```

node js client:

```
const sslCreds = await grpc.credentials.createSsl(
    fs.readFileSync('ssl/ca.crt'),
    fs.readFileSync('ssl/client.key'), // privatekey
    fs.readFileSync('ssl/client.crt'),
    {
      checkServerIdentity: checkCert,
    },
  );
  const host = 'localhost';
  const port = 8088;

  const gLogClient = new exampleGRPC.LoggerClient(
    `${host}:${port}`,
    sslCreds,
  );
```

### Environment
 - windows
 - Node version 12.17.0
 - Node installation method: nvm
 - If applicable, compiler version [e.g. clang 3.8.0-2ubuntu4]
 - Package name and version grpc 1.24.2

### Additional context

logs
```
Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (C:\james\www\project\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (C:\james\www\project\node_modules\grpc\src\client_interceptors.js:1209:28)
    at InterceptingListener._callNext (C:\james\www\project\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (C:\james\www\project\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (C:\james\www\project\node_modules\grpc\src\client_interceptors.js:847:24) {
  code: 14,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'failed to connect to all addresses'
}
```

**Comment by u007** [comment]
after a long struggle, i tried to map 127.0.0.1 to my actual domain name and it works...
or alternatively:
```
const host = 'localhost';
  const port = 8088;;
  const hostPort = `${host}:${port}`;
  const gLogClient = new synagieLogGrpc.LoggerClient(hostPort, sslCreds, {
    'grpc.ssl_target_name_override': 'actual_tlsdomain.example.com',
  });
```

**Comment by daominhsangvn** [comment]
Hi @u007, i having the same issue as your, i edited host file to map `127.0.0.1` to `example.com` but i still got the `Error: 14 UNAVAILABLE: No connection established`

This is how i generate certificates:
```
openssl genrsa -passout pass:1111 -des3 -out ca.key 4096

openssl req -passin pass:1111 -new -x509 -days 365 -key ca.key -out ca.crt -subj  "/C=US/ST=CA/L=Cupertino/O=YourCompany/OU=YourApp/CN=MyRootCA"

openssl genrsa -passout pass:1111 -des3 -out server.key 4096

openssl req -passin pass:1111 -new -key server.key -out server.csr -subj  "/C=US/ST=CA/L=Cupertino/O=YourCompany/OU=YourApp/CN=example.com"

openssl x509 -req -passin pass:1111 -days 365 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.crt

openssl rsa -passin pass:1111 -in server.key -out server.key

openssl genrsa -passout pass:1111 -des3 -out client.key 4096

openssl req -passin pass:1111 -new -key client.key -out client.csr -subj  "/C=US/ST=CA/L=Cupertino/O=YourCompany/OU=YourApp/CN=example.com"

openssl x509 -passin pass:1111 -req -days 365 -in client.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out client.crt

openssl rsa -passin pass:1111 -in client.key -out client.key

```

My BackEnd
```
var fs = require('fs');

process.env['GRPC_SSL_CIPHER_SUITES'] = 'HIGH+ECDSA'

var grpc = require("@grpc/grpc-js");
var ping_grpc_pb = require('./Ping_grpc_pb');
var PingPongService = require('./PingPong');
var cacert = fs.readFileSync("./certs/ca.crt");
var cert_chain = fs.readFileSync("./certs/server.crt");
var private_key = fs.readFileSync("./certs/server.key");

const server = new grpc.Server();

const credentials = grpc.ServerCredentials.createSsl(
    cacert, [{
        cert_chain,
        private_key
    }], true);

server.addService(ping_grpc_pb.PingPongService, new PingPongService());

server.bindAsync(`0.0.0.0:8888`, credentials, (err, port) => {
    if (err) console.error(err)
    else {
        server.start();
        console.log(`Server running at 0.0.0.0:8888`);
    }
});
```

My Client
```
const fs = require('fs')

process.env['GRPC_SSL_CIPHER_SUITES'] = 'HIGH+ECDSA'

const grpc = require('@grpc/grpc-js')
const { PingPongClient } = require('./Ping_grpc_pb');
const { Empty } = require('google-protobuf/google/protobuf/empty_pb');

var cacert = fs.readFileSync("./certs/ca.crt");
var cert_chain = fs.readFileSync("./certs/client.crt");
var private_key = fs.readFileSync("./certs/client.key");

const cred = grpc.credentials.createSsl(
    cacert,
    private_key,
    cert_chain
)

const client = new PingPongClient('localhost:8888', cred, {
    'grpc.ssl_target_name_override': 'example.com:8888',
});

process.stdin.resume();

client.sendPing(new Empty(), (err, response) => {
    console.log('SEND PING > ', err, response);
})
```

When i run the client, i got following error:
```
SEND PING >  Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (...\test\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (...\test\node_modules\@grpc\grpc-js\build\src\client.js:176:52)
    at Object.onReceiveStatus (...\test\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:334:141)
    at Object.onReceiveStatus (...\test\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:297:181)
    at ...\test\node_modules\@grpc\grpc-js\build\src\call-stream.js:130:78
    at processTicksAndRejections (node:internal/process/task_queues:75:11) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
} undefined
```

I'm using Windows 10 by the way.

**Comment by u007** [comment]
write map your etc/hosts with a dummy domain, lets say
```
127.0.0.1 mydomain.com
```

then bind on 0.0.0.0
and connect via client to mydomain.com

**Comment by daominhsangvn** [comment]
Thanks @u007  for the reply, i already have it in the host file
![image](https://user-images.githubusercontent.com/8254183/104940327-29955480-59e4-11eb-8516-86bec2d5f92b.png)
I'm using windows, is it a problem?

**Comment by u007** [comment]
try using telnet or curl or browser to access the port,
it should be a regular https port with tls support

**Comment by daominhsangvn** [comment]
@u007 I have checked with telnet and curl, the port is opened.
Where else do you want to check ?
I'm stuck at this 3 days without.

**Comment by u007** [comment]
did u follow my example? with all the cert for server and client
