### ISSUE TITLE
TypeError: util.Long.fromValue is not a function

### ISSUE THREAD

**Issue by abhishekp1996** [grpc/grpc-node#1472]
The proto file is loading correctly but it shows this error when an RPC function is called.

Version: 1.24.1
Node Version: 10.X

```
TypeError: util.Long.fromValue is not a function
at Type.IGetPaymentStatusReq$fromObject [as fromObject] (eval at Codegen (/var/www/html/api/order-service/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:9:31)
at Type.fromObject (/var/www/html/api/order-service/node_modules/@grpc/proto-loader/node_modules/protobufjs/src/type.js:538:25)
at serialize (/var/www/html/api/order-service/node_modules/@grpc/proto-loader/build/src/index.js:71:27)
at Object.final_requester.sendMessage (/var/www/html/api/order-service/node_modules/grpc/src/client_interceptors.js:807:37)
at InterceptingCall._callNext (/var/www/html/api/order-service/node_modules/grpc/src/client_interceptors.js:419:43)
at InterceptingCall.sendMessage (/var/www/html/api/order-service/node_modules/grpc/src/client_interceptors.js:464:8)
at InterceptingCall._callNext (/var/www/html/api/order-service/node_modules/grpc/src/client_interceptors.js:428:12)
at InterceptingCall.sendMessage (/var/www/html/api/order-service/node_modules/grpc/src/client_interceptors.js:464:8)
at ServiceClient.Client.makeUnaryRequest (/var/www/html/api/order-service/node_modules/grpc/src/client.js:586:21)
at ServiceClient.method_func (/var/www/html/api/order-service/node_modules/grpc/src/client.js:1000:43)
at PaymentService.<anonymous> (/var/www/html/api/order-service/dist/grpc/client/payment/client.js:53:36)
at Generator.next (<anonymous>)
at fulfilled (/var/www/html/api/order-service/dist/grpc/client/payment/client.js:4:58)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by murgatroid99** [comment]
The `@grpc/proto-loader` library uses Protobuf.js under the hood, so I suggest filing an issue with that repository: https://github.com/protobufjs/protobuf.js.
