### ISSUE TITLE
UNAVAILABLE: No connection established is emitted when calling closeClient

### ISSUE THREAD

**Issue by connor4312** [grpc/grpc-node#1487]
### Problem description

When calling `closeClient` or `client.close()`, an unavailable error can be emitted if the channel is still in the `CONNECTING` state. I believe it should not be omitted, and instead the connection simply cancelled.

### Reproduction steps

1. Create a client
2. Get it into the connected state, then
3. Immediately call client.close()

Sample stack:

```
GRPCUnavailableError: 14 UNAVAILABLE: No connection established
at Object.callErrorFromStatus (node_modules\@grpc\grpc-js\src\call.ts:81:24)      at Object.onReceiveStatus (node_modules\@grpc\grpc-js\src\client.ts:334:36) 
at Object.onReceiveStatus (node_modules\@grpc\grpc-js\src\client-interceptors.ts:434:34)
at Object.onReceiveStatus (node_modules\@grpc\grpc-js\src\client-interceptors.ts:397:48)
at Http2CallStream.outputStatus (node_modules\@grpc\grpc-js\src\call-stream.ts:230:22)
at Http2CallStream.maybeOutputStatus (node_modules\@grpc\grpc-js\src\call-stream.ts:280:14)
at Http2CallStream.endCall (node_modules\@grpc\grpc-js\src\call-stream.ts:263:12)
at Http2CallStream.cancelWithStatus (node_modules\@grpc\grpc-js\src\call-stream.ts:604:10)
at ChannelImplementation.tryPick (node_modules\@grpc\grpc-js\src\channel.ts:387:22)
at Object.updateState (node_modules\@grpc\grpc-js\src\channel.ts:212:16)    
at ResolvingLoadBalancer.updateState (node_modules\@grpc\grpc-js\src\resolving-load-balancer.ts:217:31)
at ResolvingLoadBalancer.destroy (node_modules\@grpc\grpc-js\src\resolving-load-balancer.ts:256:10)
at ChannelImplementation.close (node_modules\@grpc\grpc-js\src\channel.ts:437:32)
at ServiceClientImpl.close (node_modules\@grpc\grpc-js\src\client.ts:155:26)      at Host.resetAllServices (src\connection-pool.ts:196:19)
at ConnectionPool.markFailed (src\connection-pool.ts:372:16)
at ClientDuplexStreamImpl.<anonymous> (src\rpc.ts:141:54)
at Object.onReceiveStatus (node_modules\@grpc\grpc-js\src\client.ts:670:18) 
at Object.onReceiveStatus (node_modules\@grpc\grpc-js\src\client-interceptors.ts:397:48)
at Http2CallStream.outputStatus (node_modules\@grpc\grpc-js\src\call-stream.ts:230:22)
at Http2CallStream.maybeOutputStatus (node_modules\@grpc\grpc-js\src\call-stream.ts:280:14)
at Http2CallStream.endCall (node_modules\@grpc\grpc-js\src\call-stream.ts:263:12)
at ClientHttp2Stream.<anonymous> (node_modules\@grpc\grpc-js\src\call-stream.ts:552:14)
at emitCloseNT (internal/streams/destroy.js:69:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:61:3)
```

### Environment
 - OS name, version and architecture: Windows 1909 amd64
 - Node version 12.14.1
 - Node installation method nvm (windows)
 - If applicable, compiler version: n/a
 - Package name and version:  @grpc/grpc-js@1.0.5

**Comment by murgatroid99** [comment]
This is working as intended. Every call ends with some status if possible. UNAVAILABLE is used for connection failures, and cancelling the connection attempt is essentially a connection failure. And if you are making a streaming request you should be handling the `error` event anyway to avoid having it bubble up into the global context like you are seeing here.
