### ISSUE TITLE
Sporadic Crashes when Using Jest/JSDOM

### ISSUE THREAD

**Issue by scottfr** [grpc/grpc-node#1505]
### Problem description

When using Jest/JSDOM, setInterval() can return undefined when a window is closing. See this comment here:

https://github.com/webtorrent/bittorrent-protocol/issues/44#issuecomment-530205071

This can cause a sporadic crash with GPRC-JS. An example stack trace:

```
TypeError: Cannot read property 'unref' of undefined

      at SubchannelPool.ensureCleanupTask (node_modules/@grpc/grpc-js/src/subchannel-pool.ts:105:25)
      at SubchannelPool.getOrCreateSubchannel (node_modules/@grpc/grpc-js/src/subchannel-pool.ts:123:10)
      at Object.createSubchannel (node_modules/@grpc/grpc-js/src/channel.ts:200:36)
      at ChildLoadBalancerHandler.ChildPolicyHelper.createSubchannel (node_modules/@grpc/grpc-js/src/load-balancer-child-handler.ts:42:47)
      at subchannels.latestAddressList.map (node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:349:33)
          at Array.map (<anonymous>)
      at PickFirstLoadBalancer.connectToAddressList (node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:348:47)
      at PickFirstLoadBalancer.updateAddressList (node_modules/@grpc/grpc-js/src/load-balancer-pick-first.ts:400:12)
      at ChildLoadBalancerHandler.updateAddressList (node_modules/@grpc/grpc-js/src/load-balancer-child-handler.ts:115:19)
      at Object.onSuccessfulResolution (node_modules/@grpc/grpc-js/src/resolving-load-balancer.ts:176:32)
      at pendingLookupPromise.then (node_modules/@grpc/grpc-js/src/resolver-dns.ts:186:25)
```

The fix should be relative simple. At this point, `cleanupTimer` should be checked to make sure it is defined:

https://github.com/grpc/grpc-node/blob/ae61562be28495d64f6cfe820eea9d26aef7796d/packages/grpc-js/src/subchannel-pool.ts#L105

Happy to submit a brief PR for this if it would be helpful.

**Comment by murgatroid99** [comment]
The linked comment indicates that this is a bug in jsdom. And the corresponding jsdom issue is closed, indicating that it is fixed.

**Comment by scottfr** [comment]
Fair enough. It would be nice to get this fixed for people stuck on older versions of jsdom, but I understand it may not worth adding cruft to the codebase in cases like this.
