### ISSUE TITLE
Server shutdown hangs after client streaming method early response

### ISSUE THREAD

**Issue by aikoven** [grpc/grpc-node#1664]
### Problem description

According to [gRPC docs](https://grpc.io/docs/what-is-grpc/core-concepts/#client-streaming-rpc), a server may respond to a client streaming method before reading all of client messages. However, if the server only reads one message and then invokes a response callback, the `server.tryShutdown` callback never gets called, even after all connections are closed.

### Reproduction steps

```proto
syntax = "proto3";

package test;

service Test {
  rpc TestClientStream(stream TestRequest) returns(TestResponse){};
}

message TestRequest {}
message TestResponse {}
```

```js
const {Server, ServerCredentials, ChannelCredentials} = require('@grpc/grpc-js');
const {TestClient, TestService} = require('./test_grpc_pb');
const {TestRequest, TestResponse} = require('./test_pb');

setInterval(() => {}, 10_000);

const server = new Server();

server.addService(TestService, {
  testClientStream(call, callback) {
    call.read();
    callback(null, new TestResponse());
  },
});

server.bindAsync('localhost:8080', ServerCredentials.createInsecure(), () => {
  server.start();

  const client = new TestClient(
    'localhost:8080',
    ChannelCredentials.createInsecure(),
  );

  const stream = client.testClientStream((err, res) => {
    console.log('response', err, res?.toObject());

    client.close();

    server.tryShutdown(err => {
      console.log('shutdown', err);
    });
  });

  stream.write(new TestRequest());
  stream.write(new TestRequest());
});
```

### Environment
 - OS name, version and architecture: macOS 11.1
 - Node version: 14.3.0
 - Node installation method: homebrew 
 - Package name and version: `@grpc/grpc-js@1.2.1`

### Additional context

The logs generated by above code:

```
response null { }
```

If I remove `setInterval`, the NodeJS process would exit after response, but there's still no `shutdown` log.

I tried to add `call.destroy()` in the server method after reading a message, but no luck.

**Comment by murgatroid99** [comment]
The server code expects the inbound messages to be consumed by the application. That's what it's waiting for. You can do that without actually doing anything with the messages with a piece of code like this:

```js
stream.on('data', () => {});
```

**Comment by aikoven** [comment]
Thank you for your help.

I'm trying to read messages from stream by pulling them, not in flowing mode. To do that, I'm calling `call.read()`, but I noticed that I don't wait for `readable` event first. After adding `readable` listener, the problem goes away.

So my repro code wasn't actually modelling the case I encountered, sorry.

In my actual code I don't use stream api directly, instead consuming messages via async iteration. I tried to update repro code to have
```ts
server.addService(TestService, {
  testClientStream(call, callback) {
    Promise.resolve().then(async () => {
      for await (const item of call) {
        break;
      }

      callback(null, new TestResponse());
    });
  },
});
```
but in this case the server also shuts down cleanly.

I dug deeper, and it seems that it has something to do with how I publish messages from the client. Here's an updated repro:

```js
const {
  Server,
  ServerCredentials,
  ChannelCredentials,
} = require('@grpc/grpc-js');
const {TestClient, TestService} = require('./test_grpc_pb');
const {TestRequest, TestResponse} = require('./test_pb');

setInterval(() => {}, 10_000);

const server = new Server();

server.addService(TestService, {
  testClientStream(call, callback) {
    call.on('data', () => {
      callback(null, new TestResponse());
    });
  },
});

server.bindAsync('localhost:8080', ServerCredentials.createInsecure(), () => {
  server.start();

  const client = new TestClient(
    'localhost:8080',
    ChannelCredentials.createInsecure(),
  );

  const stream = client.testClientStream((err, res) => {
    console.log('response', err, res?.toObject());

    client.close();

    server.tryShutdown(err => {
      console.log('shutdown', err);
    });
  });

  while (true) {
    const shouldContinue = stream.write(new TestRequest());

    if (!shouldContinue) {
      break;
    }
  }
});
```

Here I'm using `data` listener on the server to respond upon first received message. On the client, I write messages until client stream buffer fills up (`stream.write()` returns false). When running this code, the `shutdown` log never appears, here's the full log:
```
response null { id: '' }
```

I also noticed that when the server responds with error, everything works fine, i.e.
```js
server.addService(TestService, {
  testClientStream(call, callback) {
    call.on('data', () => {
      callback({code: 2});
    });
  },
});
```
produces these logs:
```
response Error: 2 UNKNOWN: Unknown Error
    at Object.callErrorFromStatus (node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client.js:244:52)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:334:141)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:297:181)
    at node_modules/@grpc/grpc-js/build/src/call-stream.js:129:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 2,
  details: 'Unknown Error',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
} undefined
shutdown undefined
```
