### ISSUE TITLE
linux build fail -Werror (grpc@1.22.2 and node@14.15.4)

### ISSUE THREAD

**Issue by xenogenesi** [grpc/grpc-node#1680]
* **Node Version**: node v14.15.4 and npm 6.14.11
* **Platform**: `Linux hellspawn 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux`
* **Compiler**: cc -v `gcc version 10.2.1 20210110 (Debian 10.2.1-6)`
* **Module**: 
* 
<details><summary>Verbose output from npm install:</summary>

```
$ npm i

> grpc@1.22.2 install /src/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.22.2/node-v83-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.22.2 and node@14.15.4 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/src/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_trace.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channelz_registry.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/status_util.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_args.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression_internal.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/message_compress.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_gzip.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/stream_compression_identity.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/debug/stats_data.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/format_request.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/httpcli.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/http/parser.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/buffer_list.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/call_combiner.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/cfstream_handle.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/combiner.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_cfstream.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_posix.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_uv.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/endpoint_pair_windows.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/error.o
../deps/grpc/src/core/lib/iomgr/error.cc: In function ‘void internal_set_time(grpc_error**, grpc_error_times, gpr_timespec)’:
../deps/grpc/src/core/lib/iomgr/error.cc:267:9: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  267 |   memcpy((*err)->arena + slot, &value, sizeof(value));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../deps/grpc/src/core/lib/iomgr/error.cc:36:
../deps/grpc/src/core/lib/iomgr/error_internal.h:58:12: note: at offset 0 to object ‘grpc_error::arena’ with size 0 declared here
   58 |   intptr_t arena[0];
      |            ^~~~~
In function ‘void internal_add_error(grpc_error**, grpc_error*)’,
    inlined from ‘grpc_error* grpc_error_create(const char*, int, const grpc_slice&, grpc_error**, size_t)’ at ../deps/grpc/src/core/lib/iomgr/error.cc:357:23:
../deps/grpc/src/core/lib/iomgr/error.cc:290:9: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  290 |   memcpy((*err)->arena + slot, &new_last, sizeof(grpc_linked_error));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void internal_add_error(grpc_error**, grpc_error*)’,
    inlined from ‘grpc_error* grpc_error_add_child(grpc_error*, grpc_error*)’ at ../deps/grpc/src/core/lib/iomgr/error.cc:507:25:
../deps/grpc/src/core/lib/iomgr/error.cc:290:9: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  290 |   memcpy((*err)->arena + slot, &new_last, sizeof(grpc_linked_error));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [grpc.target.mk:514: Release/obj.target/grpc/deps/grpc/src/core/lib/iomgr/error.o] Error 1
make: Leaving directory '/src/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/alex/install/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.0-2-amd64
gyp ERR! command "/home/alex/install/bin/node" "/home/alex/install/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /src/node_modules/grpc
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/alex/install/bin/node /home/alex/install/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/src/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.10.0-2-amd64
node-pre-gyp ERR! command "/home/alex/install/bin/node" "/src/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /src/node_modules/grpc
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/alex/install/bin/node /home/alex/install/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN svelte-app@1.0.0 No repository field.
npm WARN svelte-app@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.22.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.22.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2021-01-29T14_17_20_001Z-debug.log
```

</details>

I'm trying to run `npm install`, I haven't installed node-pre-gyp, node-gyp or gprc directly, perhaps are dependencies. I've installed the project without issues some week ago, then few days ago I've upgraded node, today I needed to reinstall the project. 

I'm not sure how to proceed

**update**

<details><summary>Verbose output from npm install exporting CC=gcc-8 CXX=g++-8:</summary>

```
../deps/grpc/src/core/lib/gpr/log_linux.cc:43:13: error: ambiguating new declaration of ‘long int gettid()’
 static long gettid(void) { return syscall(__NR_gettid); }
             ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from ../deps/grpc/src/core/lib/gpr/log_linux.cc:41:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: old declaration ‘__pid_t gettid()’
 extern __pid_t gettid (void) __THROW;
                ^~~~~~
../deps/grpc/src/core/lib/gpr/log_linux.cc:43:13: error: ‘long int gettid()’ defined but not used [-Werror=unused-function]
 static long gettid(void) { return syscall(__NR_gettid); }
             ^~~~~~
cc1plus: all warnings being treated as errors
make: *** [gpr.target.mk:214: Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/log_linux.o] Error 1
make: Leaving directory '/src/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/alex/install/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.0-2-amd64
gyp ERR! command "/home/alex/install/bin/node" "/home/alex/install/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /src/node_modules/grpc
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/alex/install/bin/node /home/alex/install/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/src/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.10.0-2-amd64
node-pre-gyp ERR! command "/home/alex/install/bin/node" "/src/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /src/node_modules/grpc
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/alex/install/bin/node /home/alex/install/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/src/node_modules/grpc/src/node/extension_binary/node-v83-linux-x64-glibc --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN svelte-app@1.0.0 No repository field.
npm WARN svelte-app@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.22.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.22.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2021-02-01T06_51_47_905Z-debug.log
```
</details>

**Comment by murgatroid99** [comment]
The main issue is that `grpc` 1.22 is not compatible with Node 14. You will need a newer version of `grpc` or an older version of Node for compatibility.

However, I recommend instead switching to `@grpc/grpc-js` instead of `grpc`. It provides the same functionality, but it does not have a native addon so it does not have these compilation issues.

In either case, since you do not depend on `grpc` directly, I suggest filing an issue with whatever library you depend on that does depend on `grpc`.

**Comment by xenogenesi** [comment]
I'm not sure who I should write to. In any case, thanks for clarifying, I'll try to install another version of node, or downgrade, or use another pc.

<details><summary>Verbose output from `npx npm-remote-ls grpc`:</summary>

```
npx: installed 112 in 3.903s
└─ grpc@1.24.4
   ├─ lodash.camelcase@4.3.0
   ├─ lodash.clone@4.5.0
   ├─ body-parser@1.19.0
   │  ├─ content-type@1.0.4
   │  ├─ bytes@3.1.0
   │  ├─ depd@1.1.2
   │  ├─ http-errors@1.7.2
   │  │  ├─ depd@1.1.2
   │  │  ├─ setprototypeof@1.1.1
   │  │  ├─ inherits@2.0.3
   │  │  ├─ statuses@1.5.0
   │  │  └─ toidentifier@1.0.0
   │  ├─ debug@2.6.9
   │  │  └─ ms@2.0.0
   │  ├─ iconv-lite@0.4.24
   │  │  └─ safer-buffer@2.1.2
   │  ├─ on-finished@2.3.0
   │  │  └─ ee-first@1.1.1
   │  ├─ qs@6.7.0
   │  ├─ type-is@1.6.18
   │  │  ├─ media-typer@0.3.0
   │  │  └─ mime-types@2.1.28
   │  │     └─ mime-db@1.45.0
   │  └─ raw-body@2.4.0
   │     ├─ bytes@3.1.0
   │     ├─ unpipe@1.0.0
   │     ├─ http-errors@1.7.2
   │     └─ iconv-lite@0.4.24
   ├─ nan@2.14.2
   ├─ protobufjs@5.0.3
   │  ├─ yargs@3.32.0
   │  │  ├─ decamelize@1.2.0
   │  │  ├─ camelcase@2.1.1
   │  │  ├─ cliui@3.2.0
   │  │  │  ├─ string-width@1.0.2
   │  │  │  ├─ wrap-ansi@2.1.0
   │  │  │  │  ├─ string-width@1.0.2
   │  │  │  │  └─ strip-ansi@3.0.1
   │  │  │  └─ strip-ansi@3.0.1
   │  │  │     └─ ansi-regex@2.1.1
   │  │  ├─ os-locale@1.4.0
   │  │  │  └─ lcid@1.0.0
   │  │  │     └─ invert-kv@1.0.0
   │  │  ├─ string-width@1.0.2
   │  │  │  ├─ code-point-at@1.1.0
   │  │  │  ├─ strip-ansi@3.0.1
   │  │  │  └─ is-fullwidth-code-point@1.0.0
   │  │  │     └─ number-is-nan@1.0.1
   │  │  ├─ window-size@0.1.4
   │  │  └─ y18n@3.2.2
   │  ├─ ascli@1.0.1
   │  │  ├─ optjs@3.2.2
   │  │  └─ colour@0.7.1
   │  ├─ bytebuffer@5.0.1
   │  │  └─ long@3.2.0
   │  └─ glob@7.1.6
   │     ├─ fs.realpath@1.0.0
   │     ├─ inflight@1.0.6
   │     │  ├─ once@1.4.0
   │     │  └─ wrappy@1.0.2
   │     ├─ inherits@2.0.4
   │     ├─ minimatch@3.0.4
   │     │  └─ brace-expansion@1.1.11
   │     │     ├─ balanced-match@1.0.0
   │     │     └─ concat-map@0.0.1
   │     ├─ once@1.4.0
   │     └─ path-is-absolute@1.0.1
   ├─ express@4.17.1
   │  ├─ array-flatten@1.1.1
   │  ├─ accepts@1.3.7
   │  │  ├─ negotiator@0.6.2
   │  │  └─ mime-types@2.1.28
   │  ├─ content-disposition@0.5.3
   │  │  └─ safe-buffer@5.1.2
   │  ├─ body-parser@1.19.0
   │  ├─ content-type@1.0.4
   │  ├─ cookie@0.4.0
   │  ├─ cookie-signature@1.0.6
   │  ├─ debug@2.6.9
   │  ├─ depd@1.1.2
   │  ├─ encodeurl@1.0.2
   │  ├─ etag@1.8.1
   │  ├─ finalhandler@1.1.2
   │  │  ├─ debug@2.6.9
   │  │  ├─ escape-html@1.0.3
   │  │  ├─ on-finished@2.3.0
   │  │  ├─ encodeurl@1.0.2
   │  │  ├─ statuses@1.5.0
   │  │  ├─ unpipe@1.0.0
   │  │  └─ parseurl@1.3.3
   │  ├─ escape-html@1.0.3
   │  ├─ fresh@0.5.2
   │  ├─ merge-descriptors@1.0.1
   │  ├─ methods@1.1.2
   │  ├─ on-finished@2.3.0
   │  ├─ parseurl@1.3.3
   │  ├─ path-to-regexp@0.1.7
   │  ├─ range-parser@1.2.1
   │  ├─ proxy-addr@2.0.6
   │  │  ├─ forwarded@0.1.2
   │  │  └─ ipaddr.js@1.9.1
   │  ├─ safe-buffer@5.1.2
   │  ├─ qs@6.7.0
   │  ├─ send@0.17.1
   │  │  ├─ depd@1.1.2
   │  │  ├─ debug@2.6.9
   │  │  ├─ destroy@1.0.4
   │  │  ├─ encodeurl@1.0.2
   │  │  ├─ escape-html@1.0.3
   │  │  ├─ fresh@0.5.2
   │  │  ├─ etag@1.8.1
   │  │  ├─ http-errors@1.7.3
   │  │  │  ├─ depd@1.1.2
   │  │  │  ├─ inherits@2.0.4
   │  │  │  ├─ statuses@1.5.0
   │  │  │  ├─ setprototypeof@1.1.1
   │  │  │  └─ toidentifier@1.0.0
   │  │  ├─ mime@1.6.0
   │  │  ├─ ms@2.1.1
   │  │  ├─ on-finished@2.3.0
   │  │  ├─ range-parser@1.2.1
   │  │  └─ statuses@1.5.0
   │  ├─ serve-static@1.14.1
   │  │  ├─ encodeurl@1.0.2
   │  │  ├─ escape-html@1.0.3
   │  │  ├─ parseurl@1.3.3
   │  │  └─ send@0.17.1
   │  ├─ setprototypeof@1.1.1
   │  ├─ utils-merge@1.0.1
   │  ├─ statuses@1.5.0
   │  ├─ type-is@1.6.18
   │  └─ vary@1.1.2
   ├─ minimist@1.2.5
   ├─ istanbul@0.4.5
   │  ├─ abbrev@1.0.9
   │  ├─ async@1.5.2
   │  ├─ esprima@2.7.3
   │  ├─ escodegen@1.8.1
   │  │  ├─ estraverse@1.9.3
   │  │  ├─ esutils@2.0.3
   │  │  ├─ source-map@0.2.0
   │  │  │  └─ amdefine@1.0.1
   │  │  ├─ esprima@2.7.3
   │  │  └─ optionator@0.8.3
   │  │     ├─ deep-is@0.1.3
   │  │     ├─ prelude-ls@1.1.2
   │  │     ├─ word-wrap@1.2.3
   │  │     ├─ levn@0.3.0
   │  │     │  ├─ prelude-ls@1.1.2
   │  │     │  └─ type-check@0.3.2
   │  │     ├─ type-check@0.3.2
   │  │     │  └─ prelude-ls@1.1.2
   │  │     └─ fast-levenshtein@2.0.6
   │  ├─ glob@5.0.15
   │  │  ├─ inflight@1.0.6
   │  │  ├─ inherits@2.0.4
   │  │  ├─ minimatch@3.0.4
   │  │  ├─ path-is-absolute@1.0.1
   │  │  └─ once@1.4.0
   │  ├─ js-yaml@3.14.1
   │  │  ├─ argparse@1.0.10
   │  │  │  └─ sprintf-js@1.0.3
   │  │  └─ esprima@4.0.1
   │  ├─ mkdirp@0.5.5
   │  │  └─ minimist@1.2.5
   │  ├─ handlebars@4.7.6
   │  │  ├─ minimist@1.2.5
   │  │  ├─ wordwrap@1.0.0
   │  │  ├─ source-map@0.6.1
   │  │  ├─ neo-async@2.6.2
   │  │  └─ uglify-js@3.12.6
   │  ├─ once@1.4.0
   │  │  └─ wrappy@1.0.2
   │  ├─ nopt@3.0.6
   │  │  └─ abbrev@1.1.1
   │  ├─ supports-color@3.2.3
   │  │  └─ has-flag@1.0.0
   │  ├─ which@1.3.1
   │  │  └─ isexe@2.0.0
   │  ├─ wordwrap@1.0.0
   │  └─ resolve@1.1.7
   ├─ lodash@4.17.20
   ├─ node-forge@0.7.6
   ├─ node-pre-gyp@0.16.0
   │  ├─ detect-libc@1.0.3
   │  ├─ nopt@4.0.3
   │  │  ├─ abbrev@1.1.1
   │  │  └─ osenv@0.1.5
   │  │     ├─ os-tmpdir@1.0.2
   │  │     └─ os-homedir@1.0.2
   │  ├─ needle@2.6.0
   │  │  ├─ sax@1.2.4
   │  │  ├─ iconv-lite@0.4.24
   │  │  └─ debug@3.2.7
   │  │     └─ ms@2.1.3
   │  ├─ npm-packlist@1.4.8
   │  │  ├─ ignore-walk@3.0.3
   │  │  │  └─ minimatch@3.0.4
   │  │  ├─ npm-bundled@1.1.1
   │  │  │  └─ npm-normalize-package-bin@1.0.1
   │  │  └─ npm-normalize-package-bin@1.0.1
   │  ├─ rc@1.2.8
   │  │  ├─ deep-extend@0.6.0
   │  │  ├─ ini@1.3.8
   │  │  ├─ minimist@1.2.5
   │  │  └─ strip-json-comments@2.0.1
   │  ├─ npmlog@4.1.2
   │  │  ├─ are-we-there-yet@1.1.5
   │  │  │  ├─ delegates@1.0.0
   │  │  │  └─ readable-stream@2.3.7
   │  │  │     ├─ core-util-is@1.0.2
   │  │  │     ├─ inherits@2.0.4
   │  │  │     ├─ isarray@1.0.0
   │  │  │     ├─ process-nextick-args@2.0.1
   │  │  │     ├─ safe-buffer@5.1.2
   │  │  │     ├─ string_decoder@1.1.1
   │  │  │     │  └─ safe-buffer@5.1.2
   │  │  │     └─ util-deprecate@1.0.2
   │  │  ├─ set-blocking@2.0.0
   │  │  ├─ console-control-strings@1.1.0
   │  │  └─ gauge@2.7.4
   │  │     ├─ aproba@1.2.0
   │  │     ├─ console-control-strings@1.1.0
   │  │     ├─ signal-exit@3.0.3
   │  │     ├─ has-unicode@2.0.1
   │  │     ├─ object-assign@4.1.1
   │  │     ├─ strip-ansi@3.0.1
   │  │     ├─ string-width@1.0.2
   │  │     └─ wide-align@1.1.3
   │  │        └─ string-width@2.1.1
   │  │           ├─ is-fullwidth-code-point@2.0.0
   │  │           └─ strip-ansi@4.0.0
   │  │              └─ ansi-regex@3.0.0
   │  ├─ rimraf@2.7.1
   │  │  └─ glob@7.1.6
   │  ├─ tar@4.4.13
   │  │  ├─ chownr@1.1.4
   │  │  ├─ fs-minipass@1.2.7
   │  │  │  └─ minipass@2.9.0
   │  │  ├─ minizlib@1.3.3
   │  │  │  └─ minipass@2.9.0
   │  │  ├─ mkdirp@0.5.5
   │  │  ├─ minipass@2.9.0
   │  │  │  ├─ safe-buffer@5.2.1
   │  │  │  └─ yallist@3.1.1
   │  │  ├─ safe-buffer@5.2.1
   │  │  └─ yallist@3.1.1
   │  ├─ semver@5.7.1
   │  └─ mkdirp@0.5.5
   ├─ google-protobuf@3.14.0
   ├─ poisson-process@0.2.3
   ├─ electron-mocha@3.5.0
   │  ├─ which@1.3.1
   │  ├─ commander@2.20.3
   │  ├─ fs-extra@3.0.1
   │  │  ├─ universalify@0.1.2
   │  │  ├─ jsonfile@3.0.1
   │  │  │  └─ graceful-fs@4.2.4
   │  │  └─ graceful-fs@4.2.4
   │  ├─ mocha@3.5.3
   │  │  ├─ browser-stdout@1.3.0
   │  │  ├─ debug@2.6.8
   │  │  │  └─ ms@2.0.0
   │  │  ├─ escape-string-regexp@1.0.5
   │  │  ├─ diff@3.2.0
   │  │  ├─ growl@1.9.2
   │  │  ├─ commander@2.9.0
   │  │  │  └─ graceful-readlink@1.0.1
   │  │  ├─ json3@3.3.2
   │  │  ├─ he@1.1.1
   │  │  ├─ glob@7.1.1
   │  │  │  ├─ fs.realpath@1.0.0
   │  │  │  ├─ inherits@2.0.4
   │  │  │  ├─ inflight@1.0.6
   │  │  │  ├─ minimatch@3.0.4
   │  │  │  ├─ once@1.4.0
   │  │  │  └─ path-is-absolute@1.0.1
   │  │  ├─ mkdirp@0.5.1
   │  │  │  └─ minimist@0.0.8
   │  │  ├─ lodash.create@3.1.1
   │  │  │  ├─ lodash._baseassign@3.2.0
   │  │  │  │  ├─ lodash._basecopy@3.0.1
   │  │  │  │  └─ lodash.keys@3.1.2
   │  │  │  │     ├─ lodash._getnative@3.9.1
   │  │  │  │     ├─ lodash.isarguments@3.1.0
   │  │  │  │     └─ lodash.isarray@3.0.4
   │  │  │  ├─ lodash._basecreate@3.0.3
   │  │  │  └─ lodash._isiterateecall@3.0.9
   │  │  └─ supports-color@3.1.2
   │  │     └─ has-flag@1.0.0
   │  └─ electron-window@0.8.1
   │     └─ is-electron-renderer@2.0.1
   └─ @types/bytebuffer@5.0.42
      ├─ @types/node@14.14.22
      └─ @types/long@4.0.1
```

</details>
