### ISSUE TITLE
grpc upgrade the gcc version in a patch release

### ISSUE THREAD

**Issue by Gcaufy** [grpc/grpc-node#1702]
### Problem description

My CI process get a failure these days, which works well before. 
When I check the CI process I found the following error logs.

```
[root@c22a7f15f9de /app/node_modules]# tnpm i typescript
(node:10324) ExperimentalWarning: The fs.promises API is experimental
npm ERR! code 1
npm ERR! path /app/node_modules/grpc
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@6.1.0
npm ERR! gyp info using node@10.16.3 | linux | x64
npm ERR! gyp info find Python using Python version 2.7.5 found at "/usr/bin/python"
npm ERR! gyp info spawn /usr/bin/python
npm ERR! gyp info spawn args [ '/app/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/app/node_modules/grpc/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/app/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/10.16.3/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/10.16.3',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/app/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/10.16.3/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/grpc',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.' ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/app/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! gyp ERR! System Linux 3.10.107-1-tlinux2_kvm_guest-0049
npm ERR! gyp ERR! command "/usr/local/lib/node/bin/node" "/app/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /app/node_modules/grpc
npm ERR! gyp ERR! node -v v10.16.3
npm ERR! gyp ERR! node-gyp -v v6.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.tnpm/_logs/2021-02-25T02_59_12_695Z-debug.log
```

### Reason
It took a lot of time to trouble shot, and finally I found the reason.

1. One of my dependences in package.json depend on `grpc`.
2. `npm install` automatically upgrade the patch version to `grpc@1.24.5`
3. In `1.24.5` , it changed the C++ standard.
4. My CI env does not support `-std=c++14`

Here is the commit:
https://github.com/grpc/grpc-node/commit/6b336fd7c9479b06cbefdd43990444abe22b4bd2

### Concern

Is that change should be in a patch version? 
There are more than 100k package depend on `grpc`.
If they do not lock the patch version, they will get the same issue to.

**Comment by murgatroid99** [comment]
The error message in that log says "Undefined variable module_name in binding.gyp while trying to load binding.gyp". This has nothing to do with the C++ standard version; it's referring to a variable that is populated by `node-pre-gyp`. This is because `node-gyp` is not supposed to be called directly for `grpc`, instead it should only be called using `node-pre-gyp`. In fact, we distribute precompiled binaries for various combinations of Node version, operating system, and processing architecture, so the intention is that users should never be compiling the library, they should be installing the precompiled binaries instead.

Do you know why your CI is trying to compile grpc? Is that something `tnpm` does?

**Comment by Gcaufy** [comment]
> The error message in that log says "Undefined variable module_name in binding.gyp while trying to load binding.gyp". This has nothing to do with the C++ standard version; it's referring to a variable that is populated by `node-pre-gyp`. This is because `node-gyp` is not supposed to be called directly for `grpc`, instead it should only be called using `node-pre-gyp`. In fact, we distribute precompiled binaries for various combinations of Node version, operating system, and processing architecture, so the intention is that users should never be compiling the library, they should be installing the precompiled binaries instead.
> 

I'm pretty sure that commit cause this issue. I just don't know why npm show the log like this.
It's hard to troubleshot from that npm log. I checked every directory in the gyp args, and the grpc build directory is empty. 
So I tried to install the grpc lower version, or upgrade gcc version fix this issue.


> Do you know why your CI is trying to compile grpc? Is that something `tnpm` does?

Yes, sure, there is one package which depends on `"grpc": "^1.24.0"`, that's why it's trying install `grpc@1.24.5`.  Basiclly `tnpm` and `npm` are the same, You can treat `tnpm` as a `npm` alias which have different registry.


What I am saying is that, upgrade C++  standard, that's a big change, it may break things, should not be a patch release. because users may automatically upgrade the patch version. In the https://semver.org/, the definition of patch version is this:
>> PATCH version when you make backwards compatible bug fixes.

**Comment by murgatroid99** [comment]
The log you have provided does not even show that gcc is being called at all. It shows that node-gyp is being called in a way that does not populate the variable `module_name`. The `grpc` install script calls node-gyp using node-pre-gyp, which does populate that variable, and usually does not invoke node-gyp at all, and instead downloads the binary from the Internet. That is why I asked if `tnpm` is trying to **compile** `grpc`. Something here other than the `grpc` install script is directly invoking `node-pre-gyp` and that is the problem.

C++14 was published over 6 years ago, before we ever published `grpc`. I find it hard to believe that using it now has broken something. If you provide some evidence that the breakage was caused by that change I will look into it. Until then, I suggest that you investigate why your install process is calling node-gyp this way in the first place.

**Comment by jonapgartwohat** [comment]
I also just had the same issue in my CI env but it wasn't actually related to that environment.

For me the issue was caused by upgrading my package-lock.json file from lockfileversion 1 to lockfileversion 2 when I switched npm versions from 6->7.

In my case I was able to fix the issue by deleting the package-lock.json file and recreating it with `npm i --package-lock-only`
