### ISSUE TITLE
Compile grpc-node binaries for ARM from source code

### ISSUE THREAD

**Issue by sri-vathsa** [grpc/grpc-node#1737]
### Is your feature request related to a problem? Please describe.
I am using AWS graviton instances to host my application(node) and am facing an error during the installation of grpc saying the binary files are not found. How do I compile grpc-node binaries for ARM from source code?

### Describe the solution you'd like
Instructions to compile the binaries from source code.

### Additional context
With the increasing popularity of Apple silicon and the ARM based compute on AWS I feel this should be provided out of the box.

**Comment by murgatroid99** [comment]
What error message are you getting, exactly? We distribute precompiled binaries for `arm` and `arm64` targets, so I need to see what specifically it is looking for.

**Comment by sri-vathsa** [comment]
```
 info using node@15.11.0 | linux | arm64
 WARN Using request for node-pre-gyp https download
 info check checked for "/tmp/build/components-content-service-api-typescript--lib.6e5add716bcd41f9fc699a8db49a0499aff4e0f3/node_modules/grpc-tools/bin/grpc_tools.node" (not found)
 http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
 http 404 https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
 ERR! install error
 ERR! stack Error: 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
 ERR! stack     at Request.<anonymous> (/tmp/build/components-content-service-api-typescript--lib.6e5add716bcd41f9fc699a8db49a0499aff4e0f3/node_modules/node-pre-gyp/lib/install.js:142:27)
 ERR! stack     at Request.emit (node:events:390:22)
 ERR! stack     at Request.onRequestResponse (/tmp/build/components-content-service-api-typescript--lib.6e5add716bcd41f9fc699a8db49a0499aff4e0f3/node_modules/request/request.js:1059:10)
 ERR! stack     at ClientRequest.emit (node:events:378:20)
 ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:636:27)
 ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
 ERR! stack     at TLSSocket.socketOnData (node:_http_client:502:22)
 ERR! stack     at TLSSocket.emit (node:events:378:20)
 ERR! stack     at addChunk (node:internal/streams/readable:313:12)
 ERR! stack     at readableAddChunk (node:internal/streams/readable:288:9)
 ERR! System Linux 5.4.0-1038-aws
 ERR! command "/usr/bin/node" "/tmp/build/components-content-service-api-typescript--lib.6e5add716bcd41f9fc699a8db49a0499aff4e0f3/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
 ERR! cwd /tmp/build/components-content-service-api-typescript--lib.6e5add716bcd41f9fc699a8db49a0499aff4e0f3/node_modules/grpc-tools
 ERR! node -v v15.11.0
 ERR! node-pre-gyp -v v0.15.0
 ERR! not ok
 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by murgatroid99** [comment]
We do not distribute ARM binaries for the grpc-tools package. See #1405 for more information.

**Comment by sri-vathsa** [comment]
Can you provide instructions to generate the binaries from the source code?

**Comment by murgatroid99** [comment]
I suggest using our build script as a reference: https://github.com/grpc/grpc-node/blob/master/packages/grpc-tools/build_binaries.sh. It has some code that is specific to the architectures we build for so that part will need to be modified to support ARM.
