### ISSUE TITLE
node-pre-gyp ERR! stack Error: 520 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.1/linux-x64.tar.gz

### ISSUE THREAD

**Issue by pattrickrice** [grpc/grpc-node#1753]
Hi, I've received 520 error codes several times this week. Any idea what's going on?

```
[1/4] Resolving packages...
warning grpc-tools > node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /usr/local/share/.config/yarn/global/node_modules/grpc-tools: Command failed.
Exit code: 1
Command: node-pre-gyp install
Arguments: 
Directory: /usr/local/share/.config/yarn/global/node_modules/grpc-tools
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.15.0
node-pre-gyp info using node@12.16.1 | linux | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp info check checked for "/usr/local/share/.config/yarn/global/node_modules/grpc-tools/bin/grpc_tools.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.1/linux-x64.tar.gz
node-pre-gyp http 520 https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.1/linux-x64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 520 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.1/linux-x64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/node-pre-gyp/lib/install.js:142:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:323:22)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/needle/lib/needle.js:508:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:418:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:311:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:476:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:311:20)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
node-pre-gyp ERR! System Linux 4.15.0-101-generic
node-pre-gyp ERR! command "/root/.nvm/versions/node/v12.16.1/bin/node" "/usr/local/share/.config/yarn/global/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /usr/local/share/.config/yarn/global/node_modules/grpc-tools
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! not ok 
520 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.11.1/linux-x64.tar.gz
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by murgatroid99** [comment]
This is a transient error from the server that we use to distribute package files. If you wait a bit and try again, the error should go away.

**Comment by pattrickrice** [comment]
Just updating, I encountered the error again today. Never really encountered this error until the last 2-3 weeks when I've encountered it maybe 5-6 times.

**Comment by josephharrington** [comment]
We've seen this a few times the past few days too. 😅

**Comment by murgatroid99** [comment]
The `grpc` library has now been deprecated. We recommend using `@grpc/grpc-js` instead. It won't have this kind of problem.
