### ISSUE TITLE
How to add multiple services in grpc-js server?

### ISSUE THREAD

**Issue by bram-abe** [grpc/grpc-node#1813]
Lets say I have .proto file like below:

```
service SvcOne{
    rpc MehtodOne(RequestOne) returns (ResponseOne) {}
}

service SvcTwo{
    rpc MethodTwo(RequestTwo) returns (ResponseTwo) {}
}

message RequestOne {
    string field_req= 1;
}

message ResponseOne {
    string field_res = 1;
}

message RequestTwo {
    string field_req= 1;
}

message ResponseTwo {
    string field_res = 1;
}
```
and then I try the code like below :

```
const server = new grpc.Server();      
server.addService(protoSchema.SvcOne.service, {MehtodOne: MethodOne});
server.addService(protoSchema.SvcTwo.service, {MethodTwo: MethodTwo});
server.bindAsync(
    "0.0.0.0:50051",
    grpc.ServerCredentials.createInsecure(),
    (err) => {
      if (err) {
        console.log("Error!");
      } else {
        routeServer.start();
        console.log("Server ready...");
      }
    }
  );
```

but got an error like this :

`TypeError: Cannot read property 'service' of undefined`

So I think I missing something in between.

**The question:** How to bind multiple services (SvcOne & SvcTwo) in grpc-js server ? or is that not possible in grpc-js ?

**Comment by murgatroid99** [comment]
There shouldn't be any issue with adding multiple services to a server. Perhaps the error's stack trace could help determine what caused the error. I suggest sharing it.

**Comment by bram-abe** [comment]
> There shouldn't be any issue with adding multiple services to a server. Perhaps the error's stack trace could help determine what caused the error. I suggest sharing it.

hI @murgatroid99 below is the full stack trace I get from node:

```
D:\projects\rangkai\grpc\user-authentication\server.js:148
  server.addService(protoSchema.SvcTwo.service, {
                                       ^

TypeError: Cannot read property 'service' of undefined
    at GetServer (D:\PATH\TO\DIR\SERVER\server.js:148:40)
    at Object.<anonymous> (D:\PATH\TO\DIR\SERVER\server.js:155:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Thrown at:
    at GetServer (D:\PATH\TO\DIR\SERVER\server.js:148:40)
    at D:\PATH\TO\DIR\SERVER\server.js:155:23
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Module._load (internal/modules/cjs/loader.js:769:14)
    at executeUserEntryPoint (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(node:1760) WARNING: Exited the environment with code 1
```

**Comment by bram-abe** [comment]
> There shouldn't be any issue with adding multiple services to a server. Perhaps the error's stack trace could help determine what caused the error. I suggest sharing it.

Hi @murgatroid99 below is stack trace I get from node trace:

```
D:\PATH\TO\PROJECT\DIR\node_modules\@grpc\grpc-js\build\src\server.js:110
                impl = implFn.bind(implementation);
                              ^

TypeError: implFn.bind is not a function
    at D:\PATH\TO\PROJECT\DIR\node_modules\@grpc\grpc-js\build\src\server.js:110:31
    at Array.forEach (<anonymous>)
    at Server.addService (D:\PATH\TO\PROJECT\DIR\node_modules\@grpc\grpc-js\build\src\server.js:85:21)
    at GetServer (D:\PATH\TO\PROJECT\DIR\server.js:148:10)
    at Object.<anonymous> (D:\PATH\TO\PROJECT\DIR\server.js:155:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
Thrown at:
    at D:\PATH\TO\PROJECT\DIR\node_modules\@grpc\grpc-js\build\src\server.js:110:31
    at addService (D:\PATH\TO\PROJECT\DIR\node_modules\@grpc\grpc-js\build\src\server.js:85:21)
    at GetServer (D:\PATH\TO\PROJECT\DIR\server.js:148:10)
    at D:\PATH\TO\PROJECT\DIR\server.js:155:23
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Module._load (internal/modules/cjs/loader.js:769:14)
    at executeUserEntryPoint (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(node:6260) WARNING: Exited the environment with code 1
```

**Comment by murgatroid99** [comment]
That's a different error message than the one you had before. This new error indicates that in the implementation object, one of the fields matches the name of one of the methods in the method definition, but the value of that field is not a function, which it should be. You should check the object you are passing in at lines 148 and 155 of your `server.js`.

**Comment by bram-abe** [comment]
>This new error indicates that in the implementation object, one of the fields matches the name of one of the methods in the method definition, but the value of that field is not a function, which it should be. You should check the object you are passing in at lines 148 and 155 of your `server.js`.

Solved, I get confused between var. and func. with similiar name but difference capital letter. My bad.
