### ISSUE TITLE
Can't compile and produce the js file for proto with inner "["

### ISSUE THREAD

**Issue by ievseev** [grpc/grpc-node#1964]
Hi! I have error with compiling .proto having inner "[" char when use custom [mountebank](https://github.com/ozonru/mountebank-grpc/blob/master/src/mock.js#L40):

`error: [2021-11-11T11:36:31.231Z] - [grpc:4542] /app/node_modules/@ozonru/mountebank-grpc/src/mock.js:40
            throw new ProtoError(serviceOptions.file, error.message)
            ^

ProtoError: Could not loading a proto file "my_service.proto". Have you added a path with vendor's proto files to request? 
 Error message: illegal value '[' (protos/my_service/my_service.proto, line 440)
    at /app/node_modules/@ozonru/mountebank-grpc/src/mock.js:40:19
    at Array.forEach (<anonymous>)
    at Object.getServerInstance (/app/node_modules/@ozonru/mountebank-grpc/src/mock.js:31:37)
    at Server.<anonymous> (/app/node_modules/@ozonru/mountebank-grpc/src/index.js:22:41)
    at Object.onceWrapper (events.js:420:28)
    at Server.emit (events.js:314:20)
    at emitCloseNT (net.js:1657:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)`

In proto on line 440 file we have field:
`int64 some_id = 1 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {required: ['some_id']}];`

I assume it may be related to [this](https://github.com/protobufjs/protobuf.js/issues/1289).

Could you help to solve this problem?

**Comment by ievseev** [comment]
most likely error in method [loadSync](https://github.com/ozonru/mountebank-grpc/blob/master/src/grpc/service.js#L38)

**Comment by pytlesk4** [comment]
Running into this too

**Comment by murgatroid99** [comment]
The `@grpc/proto-loader` library just calls out to `protobufjs` to parse `.proto` files. You should file an issue there about this error.

**Comment by ievseev** [comment]
@murgatroid99 `protobufjs` fixed problem with '[' but it was in version after [5.0.3](https://github.com/grpc/grpc-node/blob/grpc%401.24.x/packages/grpc-native-core/package.json#L34). Is it possible to update protobufjs version to latest (6.11.2)?

**Comment by murgatroid99** [comment]
Fortunately, `@grpc/proto-loader` depends on `protobufjs` version `^6.10.0`, so it should install the latest version.

Though, if the `protobufjs` issue you linked in the initial issue post is the cause of this issue, then it's actually an open bug that hasn't been fixed yet, which would explain why `@grpc/proto-loader` has not picked up a fix yet.
