### ISSUE TITLE
Promisified gRPC client request throws "TypeError: Cannot read property 'checkOptionalUnaryResponseArguments' of undefined"

### ISSUE THREAD

**Issue by kivancguckiran** [grpc/grpc-node#1975]
### Problem description
Promisified grpc client request function throws unhandled exception.

### Reproduction steps
I've created a sample [repository](https://github.com/kivancguckiran/grpc-js-promisify) to reproduce the error. There is a working scenario without promisify, and an error case with promisify. I've also provided the promisify code block.

### Environment
 - Windows 10
 - v14.16.0
 - msi package
 - @grpc/grpc-js@1.4.4

### Additional context
When I try to call the promisified client request function, it throws below exception.

TypeError: Cannot read property 'checkOptionalUnaryResponseArguments' of undefined
    at makeUnaryRequest (C:\Workspace\grpc-js-promisify\node_modules\@grpc\grpc-js\build\src\client.js:122:39)        
    at C:\Workspace\grpc-js-promisify\node_modules\@grpc\grpc-js\build\src\make-client.js:104:19
    at C:\Workspace\grpc-js-promisify\withPromisify.js:6:3
    at new Promise (<anonymous>)
    at C:\Workspace\grpc-js-promisify\withPromisify.js:5:40
    at Timeout._onTimeout (C:\Workspace\grpc-js-promisify\withPromisify.js:22:3)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

Any idea why this happens? Is this a bug or am I doing something completely wrong?

Thanks in advance.

**Comment by kivancguckiran** [comment]
Seems function is not bound to client context. Works with `client.test.bind(client)`
