### ISSUE TITLE
No such Type or Enum 'type.matcher.v3.NodeMatcher'

### ISSUE THREAD

**Issue by sevaorlov** [grpc/grpc-node#2020]
### Problem description

I receive "no such Type or Enum 'type.matcher.v3.NodeMatcher' in Type .envoy.service.status.v3.ClientStatusRequest" error when trying to run my application.

There is `./node_modules/@grpc/grpc-js-xds/deps/envoy-api/envoy/type/matcher/v3/node.proto` with `type.matcher.v3.NodeMatcher` type, but I don't understand why it can't find it. 

### Reproduction steps

1. Install grpc-js-xds as a dependency to a project
2. Load grpc-js-xds with require `require('@grpc/grpc-js-xds');`

### Environment
 - OS name, version and architecture: Mac OS Big Sur 11.6
 - Node version 15.10.0
 - Node installation method nvm
 - Package name and version grpc-js-xds@1.5.1

### Additional context
Stack trace

```
Error: no such Type or Enum 'type.matcher.v3.NodeMatcher' in Type .envoy.service.status.v3.ClientStatusRequest
    at Type.lookupTypeOrEnum (<project-path>/node_modules/protobufjs/src/namespace.js:411:15)
    at Field.resolve (<project-path>/node_modules/protobufjs/src/field.js:268:94)
    at Type.resolveAll (<project-path>/node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Namespace.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Namespace.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Namespace.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Root.resolveAll (<project-path>/node_modules/protobufjs/src/namespace.js:308:25)
    at Root.resolveAll (<project-path>/node_modules/protobufjs/src/root.js:258:43)
    at Object.loadProtosWithOptionsSync (<project-path>/node_modules/@grpc/proto-loader/build/src/util.js:67:16)
    at Object.loadSync (<project-path>/node_modules/@grpc/proto-loader/build/src/index.js:194:31)
    at Object.<anonymous> (<project-path>/node_modules/@grpc/grpc-js-xds/build/src/csds.js:182:36)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (<project-path>/node_modules/@grpc/grpc-js-xds/build/src/xds-client.js:30:16)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (<project-path>/node_modules/@grpc/grpc-js-xds/build/src/resolver-xds.js:20:22)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (<project-path>/node_modules/@grpc/grpc-js-xds/build/src/index.js:20:22)
```

**Comment by murgatroid99** [comment]
Thanks for the report. This has been fixed in version 1.5.2.
