### ISSUE TITLE
Electron v13.5 and gRPC support

### ISSUE THREAD

**Issue by 0xdevelopment** [grpc/grpc-node#2042]
Problem description
We are unable use grpc with electron v13.5

Reproduction steps
npm rebuild --runtime=electron --target=13.5

Environment
OS name, version and architecture: Windows 10
Node version v14.16
Package name and version grpc@1.24.11

### Additional context
> electron-prebuilt@1.4.13 postinstall C:\Interworkalliance\token-designer-1.0.17\node_modules\electron-prebuilt
> node install.js

> grpc@1.24.11 install C:\Interworkalliance\token-designer-1.0.17\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library  

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack TypeError: Cannot read property 'major' of null
node-pre-gyp ERR! stack     at get_electron_abi (C:\Interworkalliance\token-designer-1.0.17\node_modules\grpc\node_modules\@mapbox\node-pre-gyp\lib\util\versioning.js:40:35)
node-pre-gyp ERR! stack     at get_runtime_abi (C:\Interworkalliance\token-designer-1.0.17\node_modules\grpc\node_modules\@mapbox\node-pre-gyp\lib\util\versioning.js:83:12)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (C:\Interworkalliance\token-designer-1.0.17\node_modules\grpc\node_modules\@mapbox\node-pre-gyp\lib\util\versioning.js:295:15)
node-pre-gyp ERR! stack     at install (C:\Interworkalliance\token-designer-1.0.17\node_modules\grpc\node_modules\@mapbox\node-pre-gyp\lib\install.js:190:25)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as install] (C:\Interworkalliance\token-designer-1.0.17\node_modules\grpc\node_modules\@mapbox\node-pre-gyp\lib\node-pre-gyp.js:86:37)
node-pre-gyp ERR! stack     at run (C:\Interworkalliance\token-designer-1.0.17\node_modules\grpc\node_modules\@mapbox\node-pre-gyp\lib\main.js:81:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (C:\Interworkalliance\token-designer-1.0.17\node_modules\grpc\node_modules\@mapbox\node-pre-gyp\lib\main.js:125:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1137:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:985:32)
node-pre-gyp ERR! System Windows_NT 10.0.19043
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Interworkalliance\\token-designer-1.0.17\\node_modules\\grpc\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Interworkalliance\token-designer-1.0.17\node_modules\grpc
node-pre-gyp ERR! node -v v12.18.3
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok
Cannot read property 'major' of null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.24.11 install: `node-pre-gyp install --fallback-to-build --library=static_library`      
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.24.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by murgatroid99** [comment]
The `grpc` package is deprecated. We recommend using `@grpc/grpc-js` instead.
