### ISSUE TITLE
Message less than 1MB is being truncated

### ISSUE THREAD

**Issue by rlubke** [grpc/grpc-node#2079]
### Problem description
I'm using the coherence-js-client library to store a value in a Coherence cache.  This value is `49308` bytes in length.

### Environment
 - OS name, version and architecture: [Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64
 - Node version: v14.19.1
 - Node installation method: brew
 - If applicable, compiler version: Apple clang version 13.1.6 (clang-1316.0.21.2)
 - Package name and version:  "grpc": "^1.24.9"

### Additional context
First noticed this via wireshark:

![Screen Shot 2022-04-04 at 15 02 07](https://user-images.githubusercontent.com/459724/161648453-1e0a8b71-894c-450e-ba62-faba79554ab5.png)

Looking at row `1e60`, the JSON content is truncated.

I've enabled the following debug options when running my tests:
`GRPC_VERBOSITY=debug; GRPC_TRACE=tcp,http,api,http2_stream_state`

Looking at the stream state debugging, I can see the same truncation as in the wireshark trace.

I've attached the trace output.

[trace.txt](https://github.com/grpc/grpc-node/files/8413742/trace.txt)

This is well below default limits for the grpc message size, so I'm not quite sure what's going on here.
Are there some other tuning knobs that I may need to look at or is this a bug?

**Comment by rlubke** [comment]
[repro.zip](https://github.com/grpc/grpc-node/files/8413830/repro.zip)

To reproduce:

- run `npm install`
- run `npm run coh-up`  (starts the coherence docker container)
- run `node test.js`
- run 'npm run coh-down` (when done testing, or remove via docker cli) 

The above will fail with:

```
(node:12420) UnhandledPromiseRejectionWarning: Error: 2 UNKNOWN:
    at Object.exports.createStatusError (/Users/rlubke/repro/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/rlubke/repro/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/rlubke/repro/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/rlubke/repro/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/rlubke/repro/node_modules/grpc/src/client_interceptors.js:847:24)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:12420) Error: 2 UNKNOWN:
    at Object.exports.createStatusError (/Users/rlubke/repro/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/rlubke/repro/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/rlubke/repro/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/rlubke/repro/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/rlubke/repro/node_modules/grpc/src/client_interceptors.js:847:24)
(node:12420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

If a smaller value is put to the cache, everything is fine.

**Comment by murgatroid99** [comment]
The first thing I notice is that strings in your object contain a total of 18 non-ASCII apostrophes (`’` as opposed to `'`). Each of those apostrophes is encoded with 3 bytes instead of 1, making the byte length of the JSON-encoded string 36 characters longer than the glyph length (the output of `str.length`). Your message is truncated by exactly 36 bytes. So, it looks like somewhere in the encoding pipeline, the glyph length was used where the string length was needed. That's what the weird little `event...s` strings are in the Wireshark analysis.

gRPC itself does not deal in strings, it only works with bytes, so it doesn't really have an opportunity to make this kind of error. At the moment, it looks like the two best candidates are the Coherence library, or the Protobuf library, which the Coherence library uses directly.

Also, I just want to note, related to your comment here: https://github.com/oracle/coherence-js-client/issues/42#issuecomment-1088101729, that the fact that this truncation appears in the gRPC trace logs is only evidence that the truncation is occurring on the client, not for or against the gRPC library itself being responsible for the truncation. If the gRPC library is responsible for the truncation it would show up that way in the logs, but if the gRPC library is given a truncated message to send, it will also show up that way in the logs.

As a final note, this `grpc` library has been deprecated for almost two years now, and I strongly recommend switching to its replacement `@grpc/grpc-js` if possible. For most use cases it should be a transparent drop-in replacement, requiring no changes to any code other than import/require statements. More details about specific caveats can be found in the README.

**Comment by rlubke** [comment]
Wow, good catch, thanks!  

Regarding the migration of `@grpc/grpc-js` migration, yes, will be doing so in the near future.
