### ISSUE TITLE
Google objects definition does not load if includeDirs are used

### ISSUE THREAD

**Issue by elfogre** [grpc/grpc-node#2201]
### Problem description
When I use protoLoader with includeDirs option google objects definition is not loaded

### Reproduction steps
Using the following proto:
```
syntax = "proto3";

package com.whatever;

import "google/protobuf/timestamp.proto";

service TheService {
  rpc Foo(FooRequest) returns (FooResponse) {}
}

message FooRequest {
  uint64 id = 1;
  optional google.protobuf.Timestamp check_time = 2; 
}

message FooResponse {
  uint64 id = 1;
}
```
And making calls to protoLoader from node without includeDirs, everything is OK:
```
protoLoader.loadSync("/home/jose/Desktop/test.proto", {keepCase: true,longs: String,enums: String,defaults: true,oneofs: true});
{
  'com.whatever.TheService': {
    Foo: {
      path: '/com.whatever.TheService/Foo',
      requestStream: false,
      responseStream: false,
      requestSerialize: [Function: serialize],
      requestDeserialize: [Function: deserialize],
      responseSerialize: [Function: serialize],
      responseDeserialize: [Function: deserialize],
      originalName: 'foo'
    }
  }
}
```
But if I do the same operation but using includeDirs, google Timestamp definition is not found:
```
> protoLoader.loadSync("Desktop/test.proto", {includeDirs: ["/home/jose"], keepCase: true,longs: String,enums: String,defaults: true,oneofs: true});
Uncaught:
Error: no such Type or Enum 'google.protobuf.Timestamp' in Type .com.whatever.FooRequest
    at Type.lookupTypeOrEnum (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/field.js:265:94)
    at Type.set (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/type.js:177:38)
    at Type.get (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/type.js:155:45)
    at Field.resolve (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/field.js:314:21)
    at Type.resolveAll (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (/home/jose/temp/mountebank-grpc/node_modules/protobufjs/src/root.js:246:43)
```

### Environment
 - Linux Ubuntu 22.04 amd64
 - nodejs --version v12.22.9
 - Package name and version @grpc/proto-loader@0.1.0

**Comment by murgatroid99** [comment]
Are you actually using version 0.1.0? If so, please upgrade, the latest version is 0.7.2.

**Comment by elfogre** [comment]
My bad, I did not check which one is the latest version. It was solved sometime ago :P I was using a project kinda outdated https://github.com/cbrz/mountebank-grpc/blob/master/package.json I'm going to send them a PR.

Thanks and sorry!
