### ISSUE TITLE
Cannot read properties of null (reading 'transaction')

### ISSUE THREAD

**Issue by ctleo** [grpc/grpc-node#2303]
### Problem description

I have a mesh of services and they communicate through grpc, but some services started showing the error below only in production (Kubernetes), I couldn't reproduce it locally anyway...

The connection is established between the services as below:

```
D 2022-12-27T17:18:41.293Z | dns_resolver | Looking up DNS hostname localhost
D 2022-12-27T17:18:41.293Z | connectivity_state | (22) dns:localhost:50051 IDLE -> CONNECTING
D 2022-12-27T17:18:41.296Z | dns_resolver | Resolved addresses for target dns:localhost:50051: [::1:50051,127.0.0.1:50051]
D 2022-12-27T17:18:41.297Z | connectivity_state | (22) dns:localhost:50051 CONNECTING -> CONNECTING
D 2022-12-27T17:18:41.297Z | connectivity_state | (22) dns:localhost:50051 CONNECTING -> CONNECTING
D 2022-12-27T17:18:41.298Z | connectivity_state | (22) dns:localhost:50051 CONNECTING -> CONNECTING
D 2022-12-27T17:18:41.302Z | connectivity_state | (22) dns:localhost:50051 CONNECTING -> READY
D 2022-12-27T17:18:42.295Z | connectivity_state | (22) dns:localhost:50051 READY -> READY
D 2022-12-27T17:19:11.308Z | connectivity_state | (22) dns:localhost:50051 READY -> IDLE
``` 

When a request is made the error below is displayed by the service that made the request:

```
Error: 13 INTERNAL: Cannot read properties of null (reading 'transaction')\n    at callErrorFromStatus (/api/node_modules/@grpc/grpc-js/build/src/call.js:31:19)\n    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client.js:192:76)\n    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)\n    at Object.onReceiveStatus (/api/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\n    at /api/node_modules/@grpc/grpc-js/build/src/resolving-call.js:93:78\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/api/node_modules/@grpc/grpc-js/build/src/client.js:160:34)\n    at ServiceClientImpl.<anonymous> (/api/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n
``` 

In the requested service log there is no log about the problem...

### Reproduction steps

I don't know how to reproduce the problem, it only occurs in production...

Schema:
```
syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

service RpcService {
  rpc Ping(google.protobuf.Empty) returns (google.protobuf.StringValue);
}
```

Server:
```
const packageDefinition = protoLoader.loadSync(
  path.resolve(`${__dirname}/schema.proto`),
  {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: false,
    oneofs: true,
  }
)

const RpcService: any = grpc.loadPackageDefinition(packageDefinition).RpcService

grpcServer.addService(RpcService.service, {
  Ping: async (call: any, callback: any) => {
    callback(null, { value: 'PONG' })
  },
})
``` 

Client:
```
const Loader = protoLoader.loadSync(
  path.resolve(path.join(__dirname, 'schema.proto')),
  {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: false,
    oneofs: true,
  },
)

const Service: any = grpc.loadPackageDefinition(Loader).RpcService
const instance = new Service(process.env.RPC_URI, grpc.credentials.createInsecure())

instance.Ping({}, (err: any, res: any) => {
  console.log(err, res)
})
```

### Environment

- k8s version: v1.24.5-gke.600
- Istio version: 1.14.3
- Docker image: node:16-alpine
- @grpc/grpc-js: 1.7.3
- @grpc/proto-loader: 0.7.0

**Comment by murgatroid99** [comment]
It looks like the client is reporting that it is receiving the error "Cannot read properties of null (reading 'transaction')" with the code INTERNAL from whatever it is communicating with. You say it only happens in Kubernetes, and I don't see any way that server code could produce that error, so maybe the error is coming from an intervening proxy.

**Comment by ldtorres-ratherlabs** [comment]
@ctleo How did you solve the problem with new relic?

**Comment by ctleo** [comment]
@ldtorres-ratherlabs The problem occurred when new relic was instantiated without a `license_key` configured.

To resolve, just add the `license_key` or remove the new relic
