### ISSUE TITLE
Clarify build steps for v10+

### ISSUE THREAD

**Issue by davidfiala** [grpc/grpc-node#2759]
Apologies if this is obvious, but could you please clarify the official build environment setup/steps for v10+ of grpc-js?

The master (pre v10x merge) branch included `setup_interop_purejs.sh` which I could start, let it go a while to get the base deps compiled, ctrl+c, and then jump in to packages/grpc-js and proceed from there. A hack, but worked.

In the v10 branch that file is gone, and `npm install` doesn't seem to get gulp working in my case:

```
$ npm install && gulp installAll
npm warn deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm warn deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm warn deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm warn deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@4.5.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@5.0.15: Glob versions prior to v9 are no longer supported
npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm warn deprecated glob@7.1.1: Glob versions prior to v9 are no longer supported
npm warn deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm warn deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm warn deprecated rcloader@0.2.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated glob@3.1.21: Glob versions prior to v9 are no longer supported
npm warn deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm warn deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

added 605 packages, and audited 606 packages in 10s

20 packages are looking for funding
  run `npm fund` for details

33 vulnerabilities (1 low, 5 moderate, 23 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[14:03:10] Loaded external module: ts-node/register
ReferenceError: primordials is not defined
    at fs.js:44:5
    at req_ (/home/fiala/keep3/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/fiala/keep3/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/fiala/keep3/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
  ```
  
  ```
$ node --version
v20.13.1
$ npm --version
10.8.0
```

Ubuntu 23.10 -- node using nvm

Thank you

**Comment by murgatroid99** [comment]
Basically, you have to run `npm install` in the root directory, in `packages/proto-loader`, and in `packages/grpc-js`, in that order. That script you found mostly just does that through the gulp script.
