### ISSUE TITLE
TypeError: Cannot read property 'concat' of null

### ISSUE THREAD

**Issue by dipu-bd** [grpc/grpc-node#323]
I keep getting the following error in my nodejs application. I am using `node v8.11.1` and `grpc v1.11.3`. The same code was working fine a few days ago.

```bash
    TypeError: Cannot read property 'concat' of null
        at Object.getInterceptingCall (/home/dipu/projects/tee/node_modules/grpc/src/client_interceptors.js:1376:39)
        at ServiceClient.Client.makeUnaryRequest (/home/dipu/projects/tee/node_modules/grpc/src/client.js:471:47)
        at apply (/home/dipu/projects/tee/node_modules/lodash/lodash.js:478:17)
        at ServiceClient.wrapper (/home/dipu/projects/tee/node_modules/lodash/lodash.js:5337:16)
        at Promise (/home/dipu/projects/tee/node_modules/grpc-promisify/src/index.js:22:26)
        at new Promise (<anonymous>)
        at ServiceClient.client.(anonymous function) [as getTeeFeed] (/home/dipu/projects/tee/node_modules/grpc-promisify/src/index.js:21:14)
        at Object.shadowClient.(anonymous function) [as getTeeFeed] (/home/dipu/projects/tee/build/webpack:/server/helper/grpc-client.js:40:27)
        at /home/dipu/projects/tee/build/webpack:/server/api/contents.js:31:33
        at Layer.handle [as handle_request] (/home/dipu/projects/tee/node_modules/express/lib/router/layer.js:95:5)
        at next (/home/dipu/projects/tee/node_modules/express/lib/router/route.js:137:13)
        at Route.dispatch (/home/dipu/projects/tee/node_modules/express/lib/router/route.js:112:3)
        at Layer.handle [as handle_request] (/home/dipu/projects/tee/node_modules/express/lib/router/layer.js:95:5)
        at /home/dipu/projects/tee/node_modules/express/lib/router/index.js:281:22
        at Function.process_params (/home/dipu/projects/tee/node_modules/express/lib/router/index.js:335:12)
        at next (/home/dipu/projects/tee/node_modules/express/lib/router/index.js:275:10)
```

**Comment by murgatroid99** [comment]
@drobertduke In `client_interceptors.js`, it looks like `_resolveInterceptorOverrides` can return `null`, which is then returned by `_processInterceptorLayers`, which is used by `getInterceptingCall`, but `getInterceptingCall` doesn't properly handle having a `null` value there. Is there something I'm missing here? Can you explain why it's set up that way?

**Comment by drobertduke** [comment]
@murgatroid99 The client constructor ensures that `client[functionName].interceptors` is an array, which ensures all those other calls return arrays https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/client.js#L391

@dipu-bd You are using a `grpc-promisify` library which clobbers the `client[functionName]` function, removing the `interceptors` attribute https://github.com/leaves4j/grpc-promisify/blob/master/src/index.js#L14

I can update the signatures of the private methods to only return arrays but the immediate fix here is to not clobber `client[functionName]`, and if you do, reattach `.interceptors`.

**Comment by theogravity** [comment]
Hrm, I thought doing 

`client[functionName].interceptors = originalFunction.interceptors || []`

after the promise wrapper was defined, but no go :(

anyone have the working modifications?

this is blocking me from being able to upgrade to the latest grpc client

**Comment by drobertduke** [comment]
grpc-promisify is blindly replacing all client members, including $method_names and $method_definitions. It needs to at least test that "functionName" is actually a function or that it doesn't start with "$".  Here is a working version of grpc-promisify:
```
function promisify(client) {
  Object.keys(Object.getPrototypeOf(client)).forEach(functionName => {
    if (functionName.startsWith('$')) { return; }
    const originalFunction = client[functionName];

    client[functionName] = (request, callback) => {
      if (callback && typeof callback === 'function') {
        return originalFunction.call(client, request, (error, response) => {
          callback(error, response);
        });
      }

      return new Promise((resolve, reject) => {
        originalFunction.call(client, request, (error, response) => {
          if (error) {
            reject(error);
          } else {
            resolve(response);
          }
        });
      });
    };
    client[functionName].interceptors = originalFunction.interceptors;
  });
}
```

**Comment by dipu-bd** [comment]
Thank you @drobertduke. It is clear that the problem lies in grpc-promisify module. It would be great if the main grpc module supports Promise.

**Comment by murgatroid99** [comment]
The `grpc` package has been deprecated. We recommend using `@grpc/grpc-js` instead. That library has a different interceptor implementation, which shouldn't have these issues.
