### ISSUE TITLE
Segmentation fault when using deadlines with rpc calls

### ISSUE THREAD

**Issue by villintehaspam** [grpc/grpc-node#376]
### Problem description
If I try to provide a deadline with my rpc request, the program crashes with a segmentation fault.

### Reproduction steps

Running the following code:

```javascript
'use strict';
const grpc = require('grpc');

const hello = grpc.load('hello.proto').hello;

let rpc = new hello.HelloService(
  'localhost:50001',
  grpc.credentials.createInsecure()
);

rpc.hello({}, {deadline: Date.now() + 1000}, (error, response) => {
    console.info('done.');
});

```

without anything listening results in a segmentation fault. Using a shorter deadline, or removing the deadline entirely, does not result in a segmentation fault.

### Environment
This is running in the `node:10` docker image.
Using grpc version 1.12.1.

### Additional context
The proto file:

```
syntax = "proto3";
package hello;

message HelloRequest {
}

message HelloResponse {
}

service HelloService {
    rpc Hello(HelloRequest) returns (HelloResponse);
}
```

**Comment by villintehaspam** [comment]
Using grpc version 1.11.1/2 seems to work as expected, giving a `DEADLINE_EXCEEDED` error when the deadline passes.

**Comment by nicolasnoble** [comment]
I didn't have a chance to try and reproduce it yet, but do you have a stacktrace by any chance ? These aren't necessarily easy to obtain so it's okay if you don't.

**Comment by villintehaspam** [comment]
Here you go, let me know if this was not what you wanted or if you need anything else:

```
Program received signal SIGSEGV, Segmentation fault.
grpc_closure_sched (error=0x4, c=0xb01053c112e0a01) at ../deps/grpc/src/core/lib/iomgr/closure.h:297
297     ../deps/grpc/src/core/lib/iomgr/closure.h: No such file or directory.
Missing separate debuginfos, use: debuginfo-install nodejs-10.1.0-1nodesource.x86_64
(gdb) bt
#0  grpc_closure_sched (error=0x4, c=0xb01053c112e0a01) at ../deps/grpc/src/core/lib/iomgr/closure.h:297
#1  timer_cancel (timer=<optimized out>) at ../deps/grpc/src/core/lib/iomgr/timer_custom.cc:71
#2  0x00007ffff496904d in custom_connect_callback (socket=0x23a4650, error=0x24fd150)
    at ../deps/grpc/src/core/lib/iomgr/tcp_client_custom.cc:90
#3  0x00007ffff4968f84 in tcp_connect (closure=0x24fbf10, ep=0x24fbf08, interested_parties=<optimized out>,
    channel_args=0x24fc450, resolved_addr=0x7fffffff9eb0, deadline=20060)
    at ../deps/grpc/src/core/lib/iomgr/tcp_client_custom.cc:145
#4  0x00007ffff490230a in chttp2_connector_connect (con=0x24fbea0, args=0x7fffffff9f80, result=0x24fc1b0,
    notify=0x24fc1c0) at ../deps/grpc/src/core/ext/transport/chttp2/client/chttp2_connector.cc:215
#5  0x00007ffff490f0ac in continue_connect_locked (c=0x24fc180)
    at ../deps/grpc/src/core/ext/filters/client_channel/subchannel.cc:386
#6  maybe_start_connecting_locked (c=0x24fc180) at ../deps/grpc/src/core/ext/filters/client_channel/subchannel.cc:461
#7  0x00007ffff490fcd5 in grpc_subchannel_notify_on_state_change (c=0x24fc180, interested_parties=0xdeafbeef,
    state=0x24fafac, notify=<optimized out>) at ../deps/grpc/src/core/ext/filters/client_channel/subchannel.cc:510
#8  0x00007ffff495a607 in grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>::StartConnectivityWatchLocked (
    this=<optimized out>) at ../deps/grpc/src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:304
#9  0x00007ffff495bfd4 in grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData::ProcessConnectivityChangeLocked (this=<optimized out>, connectivity_state=GRPC_CHANNEL_TRANSIENT_FAILURE, error=0x24fb290)
    at ../deps/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc:516
#10 0x00007ffff495b3fd in grpc_core::SubchannelData<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>::OnConnectivityChangedLocked (arg=0x24faf10,
    error=0x24fb290) at ../deps/grpc/src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:427
#11 0x00007ffff4922692 in grpc_combiner_continue_exec_ctx () at ../deps/grpc/src/core/lib/iomgr/combiner.cc:259
#12 0x00007ffff48df004 in grpc_core::ExecCtx::Flush (this=this@entry=0x7fffffffa140)
    at ../deps/grpc/src/core/lib/iomgr/exec_ctx.cc:131
#13 0x00007ffff496908e in ~ExecCtx (this=0x7fffffffa140, __in_chrg=<optimized out>)
    at ../deps/grpc/src/core/lib/iomgr/exec_ctx.h:96
#14 custom_connect_callback (socket=<optimized out>, error=0x24fbd30)
    at ../deps/grpc/src/core/lib/iomgr/tcp_client_custom.cc:100
#15 0x000000000097b7de in uv__stream_io ()
#16 0x0000000000981848 in uv__io_poll ()
#17 0x0000000000970cbb in uv_run ()
#18 0x0000000000880b0d in node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) ()
#19 0x000000000087fd62 in node::Start(int, char**) ()
#20 0x00007ffff6be8445 in __libc_start_main () from /lib64/libc.so.6
#21 0x0000000000845c25 in _start ()
```

**Comment by villintehaspam** [comment]
Ah! I only searched for dupes here in this repo... Feel free to close this as a duplicate if that makes sense.

**Comment by nicolasnoble** [comment]
grpc/grpc#15556 fixes it. Next release will have it.
