### ISSUE TITLE
gRPC-js doesn't pass errors onto the error handlers.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc-node#384]
### Problem description
```
(node:30511) UnhandledPromiseRejectionWarning: Error: Serialization failure
    at Http2CallStream.<anonymous> (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call.js:60:39)
    at Http2CallStream.emit (events.js:187:15)
    at Http2CallStream.endCall (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:101:18)
    at Http2CallStream.<anonymous> (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:380:30)
    at step (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:42:23)
    at Object.next (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:23:53)
    at fulfilled (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
(node:30511) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30511) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
events.js:167
      throw er; // Unhandled 'error' event
      ^
```

### Reproduction steps
Send an RPC with bad data for its proto structure.

### Environment
 - @grpc/grpc-js@0.1.0

### Additional information
Yes, the `error` event handler is attached to the call object. We should try / catch the serializer, and emit an error there instead.

**Comment by nicolasnoble** [comment]
Another one, this time when receiving a bad one:
```
(node:13753) UnhandledPromiseRejectionWarning: Error: invalid encoding
    at Http2CallStream.<anonymous> (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call.js:60:39)
    at Http2CallStream.emit (events.js:187:15)
    at Http2CallStream.endCall (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:101:18)
    at Http2CallStream.<anonymous> (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:163:30)
    at step (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:42:23)
    at Object.next (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:23:53)
    at fulfilled (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13753) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13753) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13753) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:13753) UnhandledPromiseRejectionWarning: Error: invalid encoding
    at Http2CallStream.<anonymous> (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call.js:60:39)
    at Http2CallStream.emit (events.js:187:15)
    at Http2CallStream.endCall (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:101:18)
    at Http2CallStream.<anonymous> (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:163:30)
    at step (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:42:23)
    at Object.next (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:23:53)
    at fulfilled (/home/pixel/sources/paas/node_modules/@grpc/grpc-js/build/src/call-stream.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13753) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by EskelCz** [comment]
running into the same issue

**Comment by murgatroid99** [comment]
I think this no longer happens.
