### ISSUE TITLE
Interceptors issue going from 1.9.0 to 1.13.1

### ISSUE THREAD

**Issue by eatonphil** [grpc/grpc-node#467]
I started getting this stack trace when I made a server stream request:

```
  <rejected> TypeError: Cannot read property 'concat' of null
    at ServiceClient.Client.resolveCallInterceptors (/home/phil/api/node_modules/grpc/src/client.js:418:14)
    at ServiceClient.Client.makeServerStreamRequest (/home/phil/api/node_modules/grpc/src/client.js:621:46)
    at apply (/home/phil/api/node_modules/lodash/lodash.js:478:17)
    at ServiceClient.wrapper (/home/phil/api/node_modules/lodash/lodash.js:5337:16)
    at getStream (/home/phil/api/node_modules/platform/src/pubsub.js:12:18)
    at Platform.module.exports.pullTopic (/home/phil/api/node_modules/platform/src/pubsub.js:19:18) } TypeError: Cannot read property 'concat'
 of null
    at ServiceClient.Client.resolveCallInterceptors (/home/phil/api/node_modules/grpc/src/client.js:418:14)
    at ServiceClient.Client.makeServerStreamRequest (/home/phil/api/node_modules/grpc/src/client.js:621:46)
    at apply (/home/phil/api/node_modules/lodash/lodash.js:478:17)
    at ServiceClient.wrapper (/home/phil/api/node_modules/lodash/lodash.js:5337:16)
    at getStream (/home/phil/api/node_modules/platform/src/pubsub.js:12:18)
    at Platform.module.exports.pullTopic (/home/phil/api/node_modules/platform/src/pubsub.js:19:18)
```

I was able to fix this by changing line 418 from:

`return client_interceptors.resolveInterceptorProviders(this.$interceptor_providers, method_definition).concat(this.$interceptors);`

to:

`return client_interceptors.resolveInterceptorProviders(this.$interceptor_providers || [], method_definition).concat(this.$interceptors).filter(Boolean);`

But I have no reason to believe that is an appropriate fix. What other info can I provide?

**Comment by murgatroid99** [comment]
This looks a lot like #323. I don't see grpc-promisify in your call stack, but I do see the similar `ServiceClient.wrapper`. This shouldn't happen normally because the `Client` constructor explicitly sets both `this.$interceptor_providers` and `this.interceptors` [here](https://github.com/grpc/grpc-node/blob/f941e0bc148a56a6219e7dbfe1342ac0895b1889/packages/grpc-native-core/src/client.js#L379). So there might be an issue with the way the object or methods are getting wrapped.

**Comment by eatonphil** [comment]
> So there might be an issue with the way the object or methods are getting wrapped.

Do you mean the way I'm wrapping it/how I'm using it or the way the library is currently written?

**Comment by murgatroid99** [comment]
I mean the way you're wrapping it/using it. Can you provide some code that demonstrates the problem?

**Comment by nicolasnoble** [comment]
Closing this one due to the lack of activity.
