### ISSUE TITLE
How to send a OK status code?

### ISSUE THREAD

**Issue by theogravity** [grpc/grpc-node#477]
This might be a `grpc-java` issue, but I wanted to run it by here first:

I'm using the latest `grpc-node@1.13.x` with the latest `@grpc/proto-loader@0.3.0`.

I have an RPC service in bidirectional mode, which calls `stream.end()` to end the write pipe to the client.

When our android client started using `grpc-java` version `1.13.x to latest` from `1.10.x` (using the `OkHttp` transport), we started seeing the following error messages after calling `.end()`:

```
    io.grpc.StatusRuntimeException: INTERNAL: No error: A GRPC status of OK should have been sent
    Rst Stream
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
```

For whatever reason, it thinks the connection was not 'OK' status-wise at the end, despite the entire comm flow succeeding. 

Do I need to specify this OK status (and if so, how in bi-di mode?), or might this be a bug on the `grpc-java` side?

**Comment by ejona86** [comment]
The OkHttp client is receiving a RST_STREAM with HTTP/2 error code OK. That's not normal. That sounds like a server or proxy has a bug. @nicolasnoble, is it possible for grpc-node to issue a RST_STREAM with OK?

Looking through the history from v1.10.0 to v1.13.1, I don't see too many changes that could trigger this. I did see grpc/grpc-java#4485 and grpc/grpc-java#4222, but I don't see how they could cause this behavior.

How easy is this to reproduce? @theogravity, could you narrow down the version the problem was introduced in?

**Comment by murgatroid99** [comment]
grpc-node uses the C core, and that doesn't even have an API to end a call without properly sending a status, and I think it's unlikely that the core has a bug like that.

**Comment by theogravity** [comment]
Let me see if I can create a bare-bones reproducible example. Thanks for the responses.

**Comment by murgatroid99** [comment]
The `grpc` package has been deprecated, so even if this bug still exists, we probably won't make any changes to fix it. We recommend switching to `@grpc/grpc-js`.
