### ISSUE TITLE
Better error message on `Connect Failed`

### ISSUE THREAD

**Issue by chidiwilliams** [grpc/grpc-node#531]
I'm currently using GRPC node version 1.14.1. 

I have one application that connects to multiple GRPC services. When the connection to one of the services fails, the error message I receive is:

```
{ Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (.../node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (.../node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (.../node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (.../node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (.../node_modules/grpc/src/client_interceptors.js:841:24)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' }
```

However, I would like the error to say what exact service failed, or what line number/file the error occurred to ease debugging.

**Comment by murgatroid99** [comment]
To add to that, If you have a streaming call, you should handle the `error` event on the call, and errors like this will be thrown as uncaught exceptions if you don't do that.

**Comment by chidiwilliams** [comment]
Alright, I understand, thanks.
