### ISSUE TITLE
C-ARES not being enabled, cannot use authority based dns uri

### ISSUE THREAD

**Issue by neogeno** [grpc/grpc-node#667]
### Problem description
I am able to connect to my GRPC service written in GO normally if I use an IP address.  I then switched to using a domain and it also works correct. Finally I created a new domain that for some reason can only be queried by some nameservers so I wanted to specify that when connecting so that I can skip my ISP's DNS server.

I understand this is supported using the C-ARES resolver with the format "dns://" to specify a name server authority but the connection fails now with an error about dns uri's not being supported. It seems no matter what i do it is still using the built in C based resolver. How do I make dns URI's work?

### Reproduction steps
1. npm install grpc or build from source in node project directory - changed 'GRPC_ARES=1' in gyp file as well
2. in NodeJS source, add process.env.GRPC_DNS_RESOLVER = 'ares'; var grpc = require('grpc');
3. When connecting to a GRPC service specify hostname in the format "dns://205.251.195.125/[hostname:port]

### Environment
 - OS name : Mac OS Mojave 10.14.1
 - Node version : TRIED ON BOTH: grpc@1.17.0 AND grpc@1.16.x
 - Node installation method : npm
 - Package name and version    grpc@1.17.0-dev

 ```E1204 16:12:56.903283000 4570682816 dns_resolver.cc:313]               authority based dns uri's not supported
E1204 16:12:56.903681000 4570682816 channel.cc:95]                     channel stack builder failed: {"created":"@1543911176.903664000","description":"resolver creation failed","file":"../deps/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":853}
{ Error: 2 UNKNOWN: lame client channel
    at Object.exports.createStatusError (/Users/patrickchugh/Dropbox/Dev/nodejs/grpc-node/packages/grpc-native-core/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/patrickchugh/Dropbox/Dev/nodejs/grpc-node/packages/grpc-native-core/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/patrickchugh/Dropbox/Dev/nodejs/grpc-node/packages/grpc-native-core/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/patrickchugh/Dropbox/Dev/nodejs/grpc-node/packages/grpc-native-core/src/client_interceptors.js:618:8)
    at callback (/Users/patrickchugh/Dropbox/Dev/nodejs/grpc-node/packages/grpc-native-core/src/client_interceptors.js:845:24)
  code: 2,
  metadata: Metadata { _internal_repr: {} },
  details: 'lame client channel' }```

**Comment by nicolasnoble** [comment]
grpc-node doesn't have this codepath enabled at all.

**Comment by neogeno** [comment]
Is there a reason for this? Is there any work around for my DNS issue ?

**Comment by nicolasnoble** [comment]
The mainline grpc c-ares implementation is fairly fundamentally incompatible with the grpc-node event loop architecture. It is possible to do something about it, but it'd be an amount of work that's considerably high given the low demand for the feature at the moment in nodejs.

**Comment by craigforster** [comment]
I'd love support for this feature as well.

**Comment by craigforster** [comment]
Failing that, some clear documentation that this isn't supported would be appreciated.  Perhaps https://github.com/grpc/grpc-node/blob/master/PACKAGE-COMPARISON.md shouldn't claim support for "Load Balancing"?

I got tripped up with this in June 2018 (https://groups.google.com/forum/#!topic/grpc-io/Uaq3K3TDDjU)

There's also another issue about load balancing opened in September 2018 https://github.com/grpc/grpc-node/issues/526

**Comment by craigforster** [comment]
Hopefully this PR will allow use of c-ares and resolve this issue: https://github.com/grpc/grpc-node/pull/864

**Comment by murgatroid99** [comment]
That PR has now been merged and the cares resolver can be used by setting the `GRPC_DNS_RESOLVER` environment variable in version 1.22.0-pre1. If anyone could try that version out and confirm that it works as expected that would be very helpful.
