### ISSUE TITLE
Error on running 'node-pre-gyp install --fallback-to-build --library=static_library'

### ISSUE THREAD

**Issue by eagharavol** [grpc/grpc-node#689]
### Problem description
I was testing the hyperledger fabric fabcar sample. I did the following steps:
cd /fabric-samples
cd fabcar
./startFabric.sh javascript
cd javascript
npm install

Unfortunately, I encountered with the following errors:

loadDep:fabric-client → g ▄ ╢█████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> grpc@1.14.2 install /home/ebrahim/fabric-samples/fabcar/javascript-low-level/node_modules/fabric-client/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/ebrahim/fabric-samples/fabcar/javascript-low-level/node_modules/fabric-client/node_modules/grpc/node_modules/tar/lib/parse.js:33:27)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
node-pre-gyp ERR! stack     at Module.load (module.js:344:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:301:12)
node-pre-gyp ERR! stack     at Module.require (module.js:354:17)
node-pre-gyp ERR! stack     at require (internal/module.js:12:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/home/ebrahim/fabric-samples/fabcar/javascript-low-level/node_modules/fabric-client/node_modules/grpc/node_modules/tar/lib/list.js:10:16)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! System Linux 4.15.0-43-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/ebrahim/fabric-samples/fabcar/javascript-low-level/node_modules/fabric-client/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/ebrahim/fabric-samples/fabcar/javascript-low-level/node_modules/fabric-client/node_modules/grpc
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN fabcar@1.0.0 No repository field.
npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.14.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the grpc@1.14.2 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ebrahim/fabric-samples/fabcar/javascript/npm-debug.log

### Environment
I am using Ubuntu 16.04 amd64
using node 4.2.6
installed using apt

the content of  /home/ebrahim/fabric-samples/fabcar/javascript/npm-debug.log is as follows:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
...
5737 verbose cwd /home/ebrahim/fabric-samples/fabcar/javascript
5738 error Linux 4.15.0-43-generic
5739 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
5740 error node v4.2.6
5741 error npm  v3.5.2
5742 error code ELIFECYCLE
5743 error grpc@1.14.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
5743 error Exit status 7
5744 error Failed at the grpc@1.14.2 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
5744 error Make sure you have the latest version of node.js and npm installed.
5744 error If you do, this is most likely a problem with the grpc package,
5744 error not with npm itself.
5744 error Tell the author that this fails on your system:
5744 error     node-pre-gyp install --fallback-to-build --library=static_library
5744 error You can get information on how to open an issue for this project with:
5744 error     npm bugs grpc
5744 error Or if that isn't available, you can get their info via:
5744 error     npm owner ls grpc
5744 error There is likely additional logging output above.
5745 verbose exit [ 1, true ]

**Comment by nicolasnoble** [comment]
This is an old release of both grpc and node-pre-gyp. Any chance you could update and retry?

**Comment by simplexity-ckcclc** [comment]
I have the same problem when I run the fabcar sample. I just run 'npm install grpc@1.14.2' first, and then follow the tutorial to run 'npm install' in fabcar/javascript dir. It works well for me

**Comment by simplexity-ckcclc** [comment]
I have the same problem when running the /fabric-samples/fabcar example. Here is my solution: run 'npm install grpc@1.14.2' first (before that make sure the 'node_modules' directory and 'package-lock.json' file is removed if exists). Then run 'npm install'.  That should fix the problem

**Comment by nimaafraz** [comment]
Same problem here. node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.14.2/node-v67-darwin-x64-unknown.tar.gz

**Comment by murgatroid99** [comment]
As stated above, 1.14 is a relatively old version of grpc. It does not support node 11. Please use either an older version of Node or a newer version of grpc. If you are stuck on that version of grpc because another library specifically depends on it, I suggest asking that library to upgrade their dependency.

**Comment by nimaafraz** [comment]
Downgraded to node 8, problem solved.

```
nvm use 8
npm install
```
