### ISSUE TITLE
"Internal HTTP2 error" from @grpc/grpc-js/build/src/call-stream.js:300:22

### ISSUE THREAD

**Issue by xiaozhongliu** [grpc/grpc-node#697]
### Problem description
Our apps rely on some GRPC services. Occasionally the following error occurs and breaks our logic.
Our apps were published in prod env recently, we've checked apps' metrics that there was neither traffic pressure nor restart whenever the error occurs.
```
2019-01-07 11:40:12,064 ERROR 101 [-/172.24.2.199/-/61ms GET /v1/couponUsedRecord?page=1&pageSize=10] nodejs.Error: Internal HTTP2 error
    at Http2CallStream.call.on (/app/node_modules/@grpc/grpc-js/build/src/client.js:82:45)
    at Http2CallStream.emit (events.js:187:15)
    at Http2CallStream.endCall (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:65:18)
    at ClientHttp2Stream.stream.on (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:301:22)
    at ClientHttp2Stream.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
We added a console.log into this file and got the error as below:
```
{ Error: read EHOSTUNREACH
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'EHOSTUNREACH', code: 'EHOSTUNREACH', syscall: 'read' }
```

### Reproduction steps
This error occurs occasionally, no stable reproduction method... If you need any specific stuff please tell me, thanks.

### Environment
 - OS: Alpine Linux v3.8 x86_64
 - Node: v10.15.0
 - Node installation method: official docker image: node:10.15-alpine
 - Package name and version: grpc@1.17.0

**Comment by nicolasnoble** [comment]
This kind of sounds like a bug in the nodejs runtime itself. It would be relevant to move this report to the nodejs repository itself.

**Comment by xiaozhongliu** [comment]
@nicolasnoble I see the @grpc/grpc-js package is in beta, should this issue be related with it? being not stable?

**Comment by nicolasnoble** [comment]
Even if that's the case, the nodejs runtime should never throw an internal error.

**Comment by xiaozhongliu** [comment]
@nicolasnoble We were running node 8 when the error first occurred, still the same situation after upgrading to node 10

**Comment by xiaozhongliu** [comment]
BTW, is insecure credential ok to be used in prod env for internal access? My colleague thinks this to be the possible reason.

**Comment by murgatroid99** [comment]
The important thing with the credentials is just to make sure that they match on the client and server. If the server uses insecure credentials, the client should also use insecure credentials. If the server uses SSL credentials, the client should also use SSL credentials. They are mainly just determining whether to use plaintext or an encrypted connection.

**Comment by xiaozhongliu** [comment]
Thanks for replying. We encapsulated our own grpc client with the stable grpc module and will observe it's performance continuesly.
