### ISSUE TITLE
electron 4.0.1 complains about NODE_MODULE_VERSION for grpc 1.18

### ISSUE THREAD

**Issue by kskalski** [grpc/grpc-node#711]
### Problem description
grpc_node in electron-v4.0 win32-ia32 package seems to be compiled with wrong settings (NODE_MODULE_VERSION) and electron fails to load it. Following exception is displayed:

Error: The module '\\?\D:\rep\Kogut\src\ElectronUI\node_modules\grpc\src\node\extension_binary\electron-v4.0-win32-ia32-unknown\grpc_node.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\rep\Kogut\src\ElectronUI\node_modules\grpc\src\grpc_extension.js:32:13)
    at Object.<anonymous> (D:\rep\Kogut\src\ElectronUI\node_modules\grpc\src\grpc_extension.js:64:3)

### Reproduction steps
Using electron version 4.0.1, grpc 1.18 and packaging it with electron-builder causes error described above

### Environment
 - Windows 10 x64, targeting ia32 at runtime
 - Node version: using v8.12.0 during packaging, provided by electron-4.0.1 in runtime
 - Node installation method:  "postinstall": "npm rebuild --target=4.0.1 --runtime=electron --dist-url=https://atom.io/download/electron"
 - Package name and version gRPC@1.18, Electron 4.0.1

### Additional context
Most likely it's a bug in resolution of https://github.com/grpc/grpc-node/issues/690
I guess the build should somehow apply correct NODE_MODULE_VERSION = 64 instead of (default?) 46

**Comment by kskalski** [comment]
Thanks, works for me now.
