### ISSUE TITLE
Package Definitions were loaded but grpc.loadPackageDefinition crashes

### ISSUE THREAD

**Issue by sakshamsaxena** [grpc/grpc-node#716]
### Problem description
I neatly and carefully loaded all the protos of Tensorflow Serving, and can even see the returned object populated well. However, on invoking `grpc.loadPackageDefinition()`, I'm getting a strange error which seems to be beyond me.

### Reproduction steps
It's pretty easily reproducible. You can copy paste as is the below and run it in your shell. See comments for steps :
```
mkdir demo
cd demo
# Get Tensorflow
git clone git@github.com:tensorflow/tensorflow.git
cd tensorflow
ls -a | grep -v tensorflow | xargs rm -rf
cd ../
mv ./tensorflow/tensorflow ./tensorflow
# Get Serving
git clone git@github.com:tensorflow/serving.git
cd serving
ls -a | grep -v tensorflow_serving | xargs rm -rf
cd ../
mv ./serving/tensorflow_serving ./tensorflow_serving
# Get the sample code and save it as demo.js
curl https://gist.githubusercontent.com/sakshamsaxena/1ffbc689aa198c63c108a62bfa07f3ac/raw/3115435b0769dd96b8da38a2b81952332d766ade/ServingDemoInNode.js > demo.js
# Install packages
npm i grpc @grpc/proto-loader
# Run the script!
node demo.js
```

### Environment
 - OS name, version and architecture: Win 10
 - Node version: v10.14.2 
 - Node installation method : Installer MSI
 - If applicable, compiler version : NA
 - Package name and version : `"@grpc/proto-loader": "^0.4.0", "grpc": "^1.17.0",`

### Additional context
Here's the output as is when I run the demo.js

```
[ 'tensorflow.serving.PredictionService',
  'tensorflow.serving.Class',
  'tensorflow.serving.Classifications',
  'tensorflow.serving.ClassificationResult',
  'tensorflow.serving.ClassificationRequest',
  'tensorflow.serving.ClassificationResponse',
  'tensorflow.serving.ExampleList',
  'tensorflow.serving.ExampleListWithContext',
  'tensorflow.serving.Input',
  'tensorflow.serving.ModelSpec',
  'tensorflow.serving.SignatureDefMap',
  'tensorflow.serving.GetModelMetadataRequest',
  'tensorflow.serving.GetModelMetadataResponse',
  'tensorflow.serving.InferenceTask',
  'tensorflow.serving.InferenceResult',
  'tensorflow.serving.MultiInferenceRequest',
  'tensorflow.serving.MultiInferenceResponse',
  'tensorflow.serving.Regression',
  'tensorflow.serving.RegressionResult',
  'tensorflow.serving.RegressionRequest',
  'tensorflow.serving.RegressionResponse',
  'tensorflow.serving.PredictRequest',
  'tensorflow.serving.PredictResponse',
  'tensorflow.Example',
  'tensorflow.SequenceExample',
  'tensorflow.BytesList',
  'tensorflow.FloatList',
  'tensorflow.Int64List',
  'tensorflow.Feature',
  'tensorflow.Features',
  'tensorflow.FeatureList',
  'tensorflow.FeatureLists',
  'tensorflow.MetaGraphDef',
  'tensorflow.CollectionDef',
  'tensorflow.TensorInfo',
  'tensorflow.SignatureDef',
  'tensorflow.AssetFileDef',
  'tensorflow.GraphDef',
  'tensorflow.NodeDef',
  'tensorflow.AttrValue',
  'tensorflow.NameAttrList',
  'tensorflow.TensorProto',
  'tensorflow.VariantTensorDataProto',
  'tensorflow.ResourceHandleProto',
  'tensorflow.TensorShapeProto',
  'tensorflow.DataType',
  'tensorflow.FunctionDefLibrary',
  'tensorflow.FunctionDef',
  'tensorflow.GradientDef',
  'tensorflow.OpDef',
  'tensorflow.OpDeprecation',
  'tensorflow.OpList',
  'tensorflow.VersionDef',
  'tensorflow.SaverDef',
  'google.protobuf.DoubleValue',
  'google.protobuf.FloatValue',
  'google.protobuf.Int64Value',
  'google.protobuf.UInt64Value',
  'google.protobuf.Int32Value',
  'google.protobuf.UInt32Value',
  'google.protobuf.BoolValue',
  'google.protobuf.StringValue',
  'google.protobuf.BytesValue',
  'google.protobuf.Any',
  'TensorProto' ]
D:\Personal\Projects\sampleGrpcClient\node_modules\grpc\src\client.js:963
    Object.assign(ServiceClient.prototype[name], attrs);
           ^

TypeError: Cannot assign to read only property 'name' of function 'function() {
      return requester_funcs[method_type].apply(this,
        [ attrs.path, attrs.requestSerialize...<omitted>... }'
    at Function.assign (<anonymous>)
    at Object.keys.forEach.name (D:\Personal\Projects\sampleGrpcClient\node_modules\grpc\src\client.js:963:12)
    at Array.forEach (<anonymous>)
    at Object.exports.makeClientConstructor (D:\Personal\Projects\sampleGrpcClient\node_modules\grpc\src\client.js:943:24)
    at Object.loadPackageDefintion [as loadPackageDefinition] (D:\Personal\Projects\sampleGrpcClient\node_modules\grpc\index.js:172:35)
    at Object.<anonymous> (D:\Personal\Projects\sampleGrpcClient\demo.js:21:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

**Comment by murgatroid99** [comment]
This looks like an error we were seeing that was caused by a bug in the grpc library. But that bug should be fixed in version 1.18.0. Can you confirm what version of grpc you have installed when running this code?

**Comment by sakshamsaxena** [comment]
Oh. I'm using 1.17. I see that 1.18 was very recently released. I'll try this as soon as I'm back online again. Thanks a lot!
