### ISSUE TITLE
No able to install because NPM not able to find a file

### ISSUE THREAD

**Issue by deveshaggrawal19** [grpc/grpc-node#720]
### Problem description
I am trying to install grpc but it is giving me error

### Reproduction steps
node install grpc

### Environment
 - Ubutnu 16.04 LTS
 - Node v8.15.0
 - Node installation method Direct
 - Package name gRPC

### Additional context
npm WARN fabric-shim-test@1.4.1-snapshot No repository field.
npm WARN The package fs-extra is included as both a dev and production dependency.

npm ERR! path /home/vagrant/server/fabric/fabric-chaincode-node/fabric-shim/node_modules/grpc/node_modules/mkdirp/node_modules/minimist/package.json.1618573065
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/server/fabric/fabric-chaincode-node/fabric-shim/node_modules/grpc/node_modules/mkdirp/node_modules/minimist/package.json.1618573065'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

How to proceed, please someone help

**Comment by deveshaggrawal19** [comment]
After much researching, I found out that the above problem was because of using NPM install inside a shared folder in a Vagrant environment. I don't know what was triggering it but after I try to install gRPC in another folder that was not shared I was able to successfully install it. But my actual problem is still not solved. 
I was trying to install fabric-shim so after I successfully installed gRPC then I tried to install fabric-shim but fabric shim is trying to install gRPC again and the following error pops out:

> x509@0.3.3 install /home/vagrant/fabric/sampleChaincode/node_modules/x509
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-141-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/fabric/sampleChaincode/node_modules/x509
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN sampleChaincode@1.0.0 No description
npm WARN sampleChaincode@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x509@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the x509@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Can you help me out

**Comment by deveshaggrawal19** [comment]
I found the solution, use the following to install the dependencies
sudo apt-get install build-essential

After this you should be able to able to install
