### ISSUE TITLE
Error building from source for Electron 4.1.0 on windows

### ISSUE THREAD

**Issue by sla89** [grpc/grpc-node#780]
### Problem description
Error output of command `npm run electron-build` in `packages/grpc-native-core` for branch `grpc@1.19.x`  and `master`:

```bash
  node_grpc.cc
  server.cc
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\call_credentials.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\call_credentials.cc)
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\byte_buffer.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\byte_buffer.cc)
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\node_grpc.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\node_grpc.cc)
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\call.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\call.cc)
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\channel.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\channel.cc)
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\channel_credentials.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\channel_credentials.cc)
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\server.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\server.cc)
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\completion_queue.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\completion_queue.cc)
  server_credentials.cc
  slice.cc
  timeval.cc
  win_delay_load_hook.cc
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\server_credentials.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\server_credentials.cc)
c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): error C2664: 'bool v8::Value::BooleanValue(void) const': cannot convert argument 1 from 'v8::Isolate
 *' to 'v8::Local<v8::Context>' (compiling source file ..\ext\slice.cc) [C:\dev\grpc-node\packages\grpc-native-core\build\grpc_node.vcxproj]
  c:\dev\grpc-node\packages\grpc-native-core\node_modules\nan\nan_converters_43_inl.h(60): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  (compiling source file ..\ext\slice.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--runtime=electron" "--target=4.1.0" "--disturl=https://atom.io/download/atom-shell" "--module=C:\\dev\\grpc-node\\packages\\grpc-native-core\\src\\node\\extension_binary\\electron-v4.1-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\dev\\grpc-node\\packages\\grpc-native-core\\src\\node\\extension_binary\\electron-v4.1-win32-x64-unknown" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v4.1"
gyp ERR! cwd C:\dev\grpc-node\packages\grpc-native-core
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --runtime=electron --target=4.1.0 --disturl=https://atom.io/download/atom-shell --module=C:\dev\grpc-node\packages\grpc-native-core\src\node\extension_binary\electron-v4.1-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\dev\grpc-node\packages\grpc-native-core\src\node\extension_binary\electron-v4.1-win32-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.1' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\dev\grpc-node\packages\grpc-native-core\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\grpc-node\\packages\\grpc-native-core\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "configure" "build" "--runtime=electron" "--target=4.1.0" "--disturl=https://atom.io/download/atom-shell"
node-pre-gyp ERR! cwd C:\dev\grpc-node\packages\grpc-native-core
node-pre-gyp ERR! node -v v8.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --runtime=electron --target=4.1.0 --disturl=https://atom.io/download/atom-shell --module=C:\dev\grpc-node\packages\grpc-native-core\src\node\extension_binary\electron-v4.1-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\dev\grpc-node\packages\grpc-native-core\src\node\extension_binary\electron-v4.1-win32-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.1' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.19.0 electron-build: `node-pre-gyp configure build --runtime=electron --target=4.1.0 --disturl=https://atom.io/download/atom-shell`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.19.0 electron-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

See also attached log file [2019-03-14T08_39_10_952Z-debug.log](https://github.com/grpc/grpc-node/files/2966283/2019-03-14T08_39_10_952Z-debug.log)

### Reproduction steps
Try to build electron binary from source for electron 4.1.0 from branch `grpc@1.19.x`  or `master` and setting `--target=4.1.0`  in `packages/grpc-native-core/package.json`.

When I do the same for node@10.15.3 everything works great.

### Environment
 - Windows 10 x64
 - electron 4.1.0 - node ABI 69
 - `packages/grpc-native-core`

**Comment by nicolasnoble** [comment]
I'm surprised this command exists. It's wrong. Please don't use it. It's missing the target option in it.

**Comment by sla89** [comment]
That's why I mentioned in the reproduction steps that I have set the target. :)

**Comment by ottogutierrez** [comment]
Anyone has found a fix for this? Thanks!

**Comment by nicolasnoble** [comment]
There is no steps for this. Please do not use this command.

**Comment by ottogutierrez** [comment]
Would there be a solution to have grpc built for electron? I have a project that is useless because grpc is not build for electron

**Comment by nicolasnoble** [comment]
We're still working on solving some of our compilation failures in order to provide binaries for Electron. If you want to build from sources, please read our instructions at https://github.com/grpc/grpc-node/tree/master/packages/grpc-native-core

**Comment by ottogutierrez** [comment]
Hi @nicolasnoble, sorry to bother. For building from source, you mean the instruction that states building from Git? If so, should I be cloning into my project folder structure or to an external folder?

Thanks!

**Comment by nicolasnoble** [comment]
The same instructions apply to both, really. You need to tweak your openssl headers you get from node-gyp due to symbol collision. You can do this from either git source or npm source.

**Comment by dansteen** [comment]
hi @nicolasnoble we are also having this issue.  Is there some documentation somewhere that will tell us specifically what we need to tweak to get this to work?  (we are actually trying to build for the new v5 beta of Electron)

**Comment by nicolasnoble** [comment]
It's usually impossible to build for beta versions of electron due to missing headers files.

**Comment by dansteen** [comment]
Thanks for the response!   If we were to go back to v4, would there be a set of instructions somewhere that we could follow?

**Comment by nicolasnoble** [comment]
The one that I posted a few posts up: https://github.com/grpc/grpc-node/tree/master/packages/grpc-native-core

**Comment by dansteen** [comment]
ah! I see.  so you guys have the header replacement stuff built into the build process?  And that's why you need to explicitly support different electron versions since that stuff changes from version to version (is that a correct understanding?)

We have a good relationship with some of the core electron devs.   If I could get the missing header files, would there be something I could do to help get a v5 build process going?

**Comment by nicolasnoble** [comment]
There's two sets of headers we are taking about here. The first one is the openssl headers that are always conflicting and we need to swap these out. The second is the fact node-gyp doesn't know where or how to get the electron beta headers when building.

**Comment by murgatroid99** [comment]
To clarify, for Electron in particular, we don't do anything with OpenSSL headers.

Still, it will likely not help to simply have a copy of the Electron headers. As mentioned, our build process involves downloading the headers from the Electron website. I don't think it's worth it to have a new temporary build process just while waiting for them to publish their headers.

**Comment by dansteen** [comment]
Ah.  Thanks for the clarification.   That makes sense - thanks for taking the time to explain.

**Comment by nicolasnoble** [comment]
Yes, sorry. The OpenSSL headers trick is only relevant for building the nodejs Windows module, not the Electron one.
