### ISSUE TITLE
Self-signed certs aren't working

### ISSUE THREAD

**Issue by brandonros** [grpc/grpc-node#800]
```
const grpc = require('grpc')

const credentials = grpc.credentials.createSsl()
const connectionOptions = {
  'grpc.ssl_target_name_override': 'redacted-2',
  'grpc.default_authority': 'redacted-2'
}
const client = new grpc.Client('redacted-1', credentials, connectionOptions)

const path = '/UserInfoService/getPrimaryUserInfo'
const encoder = () => Buffer.from('Hello, world')
const decoder = () => Buffer.from('Hello, world')
const request = Buffer.from('Hello, world')
const metadata = {}
const options = {}

client.makeUnaryRequest(path, encoder, decoder, metadata, options, (err, res) => {
  if (err) {
    console.error(err)
    return
  }
  console.log(res)
})
```

```
$ node index.js
E0321 11:42:46.549190000 140736104977280 ssl_transport_security.cc:1239] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
E0321 11:42:46.715823000 140736104977280 ssl_transport_security.cc:1239] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
{ Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' }
```

`$ openssl s_client -showcerts -connect redacted-1`

```
CONNECTED(00000006)
depth=2 C = US, L = Remote, O = redacted, OU = redacted, CN = redacted CA 2018-02-02
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/CN=redacted-1
   i:/CN=redacted-2
-----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
 1 s:/CN=redacted-2
   i:/C=US/L=Remote/O=redacted/OU=redacted/CN=redacted CA 2018-02-02
-----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
 2 s:/C=US/L=Remote/O=redacted/OU=redacted/CN=redacted CA 2018-02-02
   i:/C=US/L=Remote/O=redacted/OU=redacted/CN=redacted CA 2018-02-02
-----BEGIN CERTIFICATE-----
REDACTED
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=redacted-1
issuer=/CN=redacted-2
---
No client certificate CA names sent
---
SSL handshake has read 2809 bytes and written 444 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: REDACTED
    Session-ID-ctx: 
    Master-Key: REDACTED
    Start Time: 1553182837
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

`"grpc": "^1.19.0"`

**Comment by brandonros** [comment]
I was able to solve it with something like this:

```
const rootCert = fs.readFileSync('redacted.pem')
const credentials = grpc.credentials.createSsl(rootCert)
```

**Comment by nicolasnoble** [comment]
Since you've heavily modified the reproduction case, there isn't much of a reproduction we can do on our side.

Self signed certificates should work. Could you please provide us with a reproduction case we can actually run? You may simply create another set of certificates that do not contain any sensitive information and then share everything.

**Comment by brandonros** [comment]
```
$ node index.js 
{ Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/bros/Desktop/node-grpc/node_modules/grpc/src/client_interceptors.js:845:24)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' }
```

@nicolasnoble Does this look to be SSL related to you?

**Comment by nicolasnoble** [comment]
Try with the following environment variables:

```
export GRPC_VERBOSITY=DEBUG
export GRPC_TRACE=tcp,secure_endpoint,transport_security
```

Be advise this will spew a lot of information, and possibly leak confidential data.
