### ISSUE TITLE
Build failed when `node-pre-gyp` use `needle` module

### ISSUE THREAD

**Issue by niklaus0823** [grpc/grpc-node#880]
### Problem description
Build failed when `node-pre-gyp` use `needle` module

Add dependencies, and it can be fixed。

``` json
...
"dependencies": {
    "node-pre-gyp": "^0.12.0",
    "request": "^2.88.0"
},
...
```

https://github.com/grpc/grpc-node/blob/2ab15fef4ff19d02b78f33a0290ca10f6978262b/packages/grpc-tools/package.json#L27-L29

### Reproduction steps
``` bash
npm install grpc-tools -g
``` 

### Environment
 - Darwin 18.6.0
 - Node  v11.10.1
 - Npm v6.9

### Additional context

``` bash
npm install grpc-tools -g
/usr/local/bin/grpc_tools_node_protoc -> /usr/local/lib/node_modules/grpc-tools/bin/protoc.js
/usr/local/bin/grpc_tools_node_protoc_plugin -> /usr/local/lib/node_modules/grpc-tools/bin/protoc_plugin.js

> grpc-tools@1.7.3 install /usr/local/lib/node_modules/grpc-tools
> node-pre-gyp install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: There was a fatal problem while downloading/extracting the tarball
node-pre-gyp ERR! stack     at Unpack.afterTarball (/usr/local/lib/node_modules/grpc-tools/node_modules/node-pre-gyp/lib/install.js:102:33)
node-pre-gyp ERR! stack     at Unpack.emit (events.js:197:13)
node-pre-gyp ERR! stack     at Unpack.[maybeClose] (/usr/local/lib/node_modules/grpc-tools/node_modules/tar/lib/unpack.js:171:12)
node-pre-gyp ERR! stack     at Unpack.opt.ondone._ (/usr/local/lib/node_modules/grpc-tools/node_modules/tar/lib/unpack.js:89:23)
node-pre-gyp ERR! stack     at Unpack.emit (events.js:197:13)
node-pre-gyp ERR! stack     at Unpack.[emit] (/usr/local/lib/node_modules/grpc-tools/node_modules/tar/lib/parse.js:230:12)
node-pre-gyp ERR! stack     at Unpack.[maybeEnd] (/usr/local/lib/node_modules/grpc-tools/node_modules/tar/lib/parse.js:346:17)
node-pre-gyp ERR! stack     at Unpack.[consumeChunk] (/usr/local/lib/node_modules/grpc-tools/node_modules/tar/lib/parse.js:354:21)
node-pre-gyp ERR! stack     at Unpack.write (/usr/local/lib/node_modules/grpc-tools/node_modules/tar/lib/parse.js:310:25)
node-pre-gyp ERR! stack     at Unpack.end (/usr/local/lib/node_modules/grpc-tools/node_modules/tar/lib/parse.js:419:14)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/11.10.1/bin/node" "/usr/local/lib/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/grpc-tools
node-pre-gyp ERR! node -v v11.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
There was a fatal problem while downloading/extracting the tarball
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc-tools@1.7.3 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc-tools@1.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
···

**Comment by nicolasnoble** [comment]
This is a node-pre-gyp issue, not a grpc issue.

**Comment by niklaus0823** [comment]
ok, thanks
