### ISSUE TITLE
Interop clients and servers failing - Invalid value for global._client_implementation

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc-node#89]
example error stack trace:

```
2017-11-13 17:26:55,822 /var/local/git/grpc-node/test/any_grpc.js:9
    throw new Error([
    ^

Error: Invalid value for global._client_implementation: undefined. If running from the command line, please --require a fixture first.
    at getImplementation (/var/local/git/grpc-node/test/any_grpc.js:9:11)
    at Object.<anonymous> (/var/local/git/grpc-node/test/any_grpc.js:23:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/local/git/grpc-node/test/interop/interop_client.js:23:12)

2017-11-13 17:26:55,822 FAILED: cloud_to_prod:node:default:empty_unary [ret=1, pid=20612, time=1.0sec]
```

seen in https://sponge.corp.google.com/target?id=de78aca9-7303-4ddf-98ed-a6ad111c1fd1&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS (cloud to prod) and https://sponge.corp.google.com/target?id=dd531fd9-274b-4aa7-9e3f-1e89e67f1d35&target=grpc/ubuntu/pull_request/grpc_interop_tocloud&searchFor=&show=ALL&sortBy=STATUS (cloud to cloud)

**Comment by jtattermusch** [comment]
This breaks 100% of interop tests runs. Please handle with priority.
