### ISSUE TITLE
unhandled promise rejection: Header field "authorization" must only have a single value

### ISSUE THREAD

**Issue by alexander-fenster** [grpc/grpc-node#894]
### Problem description

In `grpc-js` v0.4.1, some client libraries fail with unhandled promise rejection described here: https://github.com/googleapis/nodejs-vision/issues/391

```
"message": {
    "code": "ERR_HTTP2_HEADER_SINGLE_VALUE",
    "details": "Getting metadata from plugin failed with error: Header field \"authorization\" must only have a single value",
    "metadata": {
      "internalRepr": []
    },
    "note": "Exception occurred in retry method that was not classified as transient"
  }
```

### Reproduction steps

Follow the steps from the @google-cloud/vision issue linked above.

### Environment
 - OS name, version and architecture: Linux
 - Node version: 8.15.0, 10.16.0
 - Node installation method: official tarball
 - If applicable, compiler version: N/A
 - Package name and version: `@grpc/grpc-js` v0.4.1

**Comment by jamesvnz** [comment]
I had the same error message with v0.4.1

Reverting to v0.4.0 has cleared the issue for me.

**Comment by tcha-tcho** [comment]
It looks that this problem is back:
```
✔  functions: Using node@10 from host.
✔  functions: Emulator running at http://localhost:5001
i  functions: Beginning execution of "getSpaces"
⚠  Default "firebase-admin" instance created!
⚠  The Cloud Firestore emulator is not running so database operations will fail with a 'default credentials' error.
⚠  Google API requested!
   - URL: "https://www.googleapis.com/oauth2/v4/token"
   - Be careful, this may be a production service.
>  (node:20785) UnhandledPromiseRejectionWarning: Error: Getting metadata from plugin failed with error: Header field "authorization" must only have a single value
>      at Http2CallStream.call.on (/Users/malpelibook/Documents/codes/unnon/functions/node_modules/@grpc/grpc-js/build/src/call.js:68:41)
>      at Http2CallStream.emit (events.js:194:15)
>      at process.nextTick (/Users/malpelibook/Documents/codes/unnon/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
>      at process._tickCallback (internal/process/next_tick.js:61:11)
>  (node:20785) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
>  (node:20785) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
My package.json

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase experimental:functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "@google-cloud/logging": "^5.2.1",
    "@google-cloud/storage": "^3.1.0",
    "@google-cloud/translate": "^4.1.3",
    "@google-cloud/vision": "^1.2.0",
    "child-process-promise": "^2.2.1",
    "city-timezones": "^1.1.0",
    "cloudinary": "^1.14.0",
    "cors": "^2.8.5",
    "country-language": "^0.1.7",
    "curl-request": "^1.1.1",
    "firebase": "^6.4.0",
    "firebase-admin": "^8.3.0",
    "firebase-functions": "^3.0.2",
    "firebase-functions-test": "^0.1.6",
    "firebase-tools": "^7.2.4",
    "glob": "^7.1.4",
    "grpc": "^1.23.1",
    "html-entities": "^1.2.1",
    "imgix-core-js": "^2.1.0",
    "mkdirp": "^0.5.1",
    "mkdirp-promise": "^5.0.1",
    "moniker": "^0.1.2",
    "node-emoji": "^1.10.0",
    "node-libcurl": "^2.0.1",
    "opengraph-io": "^1.1.2",
    "request": "^2.88.0",
    "request-promise": "^4.2.4",
    "stripe": "^7.8.0"
  },
  "engines": {
    "node": "10"
  },
  "private": true
}
```
I also take a look on the `call.js` and it seems that it came from a `@grpc/grpc-js@0.5.2`.

Thank you for any help! :)
