### ISSUE TITLE
@grpc/gprc-js: EventEmitter leak for drain/close/error

### ISSUE THREAD

**Issue by schmidt-sebastian** [grpc/grpc-node#916]
See https://github.com/googleapis/nodejs-firestore/issues/661#issuecomment-501799535

Firestore customers (on `@grpc/grpc-js 0.4.3) are reporting that they are still seeing EventEmitter leak warnings, albeit not for `connectivityStateChanged` listeners.

Instead, they see:

```
(node:48004) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:48004) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:48004) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by schmidt-sebastian** [comment]
@murgatroid99

**Comment by jmacedoit** [comment]
@murgatroid99 I'm trying to reproduce it again, it appears to be harder to do so than before. Will let you know when I have a stack trace for you.

**Comment by jmacedoit** [comment]
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:251:17)
    at DestroyableTransform.addListener (events.js:267:10)
    at DestroyableTransform.Readable.on (/Users/xxx/Projects/yyy/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:786:33)
    at BunWrapper.Stream.pipe (internal/streams/legacy.js:28:8)
    at _firestore.readWriteStream.then.backendStream (/Users/xxx/Projects/yyy/node_modules/@google-cloud/firestore/build/src/watch.js:343:35)
(node:66877) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:251:17)
    at DestroyableTransform.addListener (events.js:267:10)
    at DestroyableTransform.Readable.on (/Users/xxx/Projects/yyy/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:786:33)
    at BunWrapper.Stream.pipe (internal/streams/legacy.js:62:8)
    at _firestore.readWriteStream.then.backendStream (/Users/xxx/Projects/yyy/node_modules/@google-cloud/firestore/build/src/watch.js:343:35)
(node:66877) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:251:17)
    at DestroyableTransform.addListener (events.js:267:10)
    at DestroyableTransform.Readable.on (/Users/xxx/Projects/yyy/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:786:33)
    at BunWrapper.Stream.pipe (internal/streams/legacy.js:84:8)
    at _firestore.readWriteStream.then.backendStream (/Users/xxx/Projects/yyy/node_modules/@google-cloud/firestore/build/src/watch.js:343:35)
```

There it is. I still need to run some extra tests to understand the conditions in which this happens.

**Comment by murgatroid99** [comment]
Those call stacks don't say grpc-js anywhere. I don't think this one is actually a grpc-js issue.

**Comment by schmidt-sebastian** [comment]
I'll see if I can repro this. This might be an issue in Firestore.

**Comment by schmidt-sebastian** [comment]
I am not able to come up with a test case, but this seems to be happening in our Watch code. On re-connect, we pipe back to the original stream. I suspect that this is happening when we have more than 10 reconnect attempts.

I am closing this issue for now - will resolve this as part of https://github.com/googleapis/nodejs-firestore/issues/661
